### ISSUE TITLE
Building Infrastructure / Towers 

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#10]
# **Description**
Team 7 intends to implement the initial classes and methods used in creating game infrastructure, e.g. towers, walls, bridges, etc. These classes will include attributes and baseline state values (health / damage / range) which will be manipulated to create unique instances of all the gameplay infrastructure. Given the genre of the game, building infrastructure is critical for the game, providing the player with a means to defend their crystal and win the game. Upon starting a level during the daytime cycle the player will be able to build infrastructure in designated grid locations. 

## Ranged Buildings
Ranged buildings are the staple of a tower defense game, damaging enemies once they enter their given range.

## Building Interface
All buildings will need to have an interface which provides the player basic information regarding their attributes, as well as methods to repair / upgrade the buildings. 

# **Dependencies**
This feature has the following dependencies: 
- Build state terrain and a collision detection model, #6

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create baseline infrastructure class #25  (Aug. 20)
- [x] Design structure types #29 (Aug. 23)
- [x] Create defensive building #52 (Aug. 27)
- [x] Create static infrastructure #53 (Aug. 27)
- [x] Spawn building in map #27 (Aug. 28)
- [x] Test all features (Aug. 29) 

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [x] Test towers damage / kill enemies
- [ ] Create building interface
- [ ] Implement UI element and functionality to repair infrastructure
- [ ] Implement functionality to upgrade infrastructure

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- 
# **Members**

- Harland (@harland-jensen) (Harry Jensen)
- Emma (@schmidem) (Emma Schmidley)
- Jonathan (@jonooallen) (Jonathan Allen) 
- Congxiao (@CongxiaoZhou) (Congxiao Zhou)

**Comment by mackenziekerr1** [comment]
Hey Team 7, just jumping on here on behalf of the Shop feature team to clarify some things from our discussion this morning. For sprint 1, we will focus on implementing a shop interface dealing only in 1 currency with only 1 item available from the shop to ensure that basic functionality is correct - In future sprints, we can implement features such as purchasing & placing buildings. Let me know if you have any questions or if any of the above is incorrect!

**Comment by sukizzz** [comment]
Hey Team 7, just a quick revision about what we (Team 5) discussed with you guys in the studio on Wednesday. We talked about how we going to handle our buildings differently e.g. we will be resource collectors, and your team will be managing attack / defence). Furthermore, we agreed that from the shop all buildings were to be bought in stone. In regards to coding, we are going to code the resources assuming it extends a basic building class that you guys make ( we are happy to help with that but because you have more buildings to create it was decided in the best interests of everyone to leave with you) Intend to check in next week about how we're all going and if designs and colour pallets are along the same line. Let me know if you guys have any questions :))

**Comment by cholnhial** [comment]
Hey @jonooallen, I noticed that the healthbar doesn't sit quiet right on the tower. There appears to be no space in between.
<img width="83" alt="image" src="https://user-images.githubusercontent.com/4253382/187016416-44ef8b64-095f-4260-885e-0aa3b2431473.png">

 Perhaps we can turn this into a bug and I'll introduce a way to add padding above entities, which can be passed as part of a 3 argument constructor in addition to the existing one. Let me know what you think.

**Comment by jonooallen** [comment]
> Hey @jonooallen, I noticed that the healthbar doesn't sit quiet right on the tower. There appears to be no space in between.
> <img width="83" alt="image" src="https://user-images.githubusercontent.com/4253382/187016416-44ef8b64-095f-4260-885e-0aa3b2431473.png">
> 
>  Perhaps we can turn this into a bug and I'll introduce a way to add padding above entities, which can be passed as part of a 3 argument constructor in addition to the existing one. Let me know what you think. 

These images are placeholders and will be changed before end of sprint 1. Upon adding the final images I will align and position the health bar appropriately thanks.

**Comment by cholnhial** [comment]
> 

Awesome. I'm happy for you to make changes to the healthbar component. Should you have any questions reach out to me as I introduced it into the game. i'm in team 9 channel.

**Comment by cholnhial** [comment]
> > Hey @jonooallen, I noticed that the healthbar doesn't sit quiet right on the tower. There appears to be no space in between.
> > <img alt="image" width="83" src="https://user-images.githubusercontent.com/4253382/187016416-44ef8b64-095f-4260-885e-0aa3b2431473.png">
> > Perhaps we can turn this into a bug and I'll introduce a way to add padding above entities, which can be passed as part of a 3 argument constructor in addition to the existing one. Let me know what you think.
> 
> These images are placeholders and will be changed before end of sprint 1. Upon adding the final images I will align and position the health bar appropriately thanks. Additionally, having a health bar on every entity, especially the structures, looks crowded and as a team we are debating whether to keep them attached or not (TBD).

Regarding the crowdedness, we were thinking on either showing it on hover. So we can additional behaviour so it hides unless the player hovers or when some condition is met.
