### ISSUE TITLE
Work with Team 7 to integrate the code

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#100]
# **Description**
Integrating the code of the UI Building interface will take calling the work already interplanted by Team 7, statistics from the game, and also the design built by team 10. This implementation will also require code to build the UI interface and linkage to other works. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

**Goal 1 (Sep 5)**
- [x] Implementing the designs made by the team into the game

**Goal 2 (Sep 8)**
- [x] Have the UI interface pop-up on click 
- [x] Have the exit button implemented and you can close the pop-up
- [x] Work with Team 7 to integrate the code that has already been established
- [ ] JUnit tests to be made

**Goal 3 (Sep. 11)**
- [x] Final User Testing to be completed to determine any bugs in the code
- [x] Fix any last issues with the code and determine functionality 

**Completion Deadline:** September 14

# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)
