### ISSUE TITLE
Day & Night Cycle 

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#101]
# **Description**
This feature tickets regards the implementation of a day and night cycle into the game. It informs the game of certain events that happen during the night i.e. during the day cycle the user will build and gather resources, buy and sell property and artifacts in preparation of the night cycle. During which enemies will spawn, attack, and kill the character, resources, and crystal. If successful, the game will end. This allows for game variation - as the nights progress enemies become more advanced. There will be x amount of day and night cycles, with the day cycle duration = x, while the night cycle duration = y. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Ability to cycle through the day and night (Sep. 5)
- [x] Ability to inform (event trigger) other game components (Sep. 8)
- [x] Day and night clock sprites (Sep. 8)
- [x] Implementation of clock (Sep. 9)

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [x] Night cycle filter (Sep. 12)

# **Documentation** (to be updated!!)
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
