### ISSUE TITLE
Day & Night Cycle Timer

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#102]
# **Description**
**Feature:** [Day and Night Cycle ](#101)

The game cycle will start at DAY and proceed to NIGHT. Visa Versa! Each of the cycles should be adjustable, to allow for later development. This will be achieved through a JSON file. It will use the existing game facility for the timing. This will form the basis of anything that needs to know whether it is DAY or NIGHT. 
DAY cycle: 60%, NIGHT cycle: 30%. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Brainstorm UML class (Sep. 3)
- [x] Create class file (Sep. 5)
- [x] Create JSON file (Sep. 5)
- [x] Implementation of class (Sep. 5)
- [x] Unit tests (Sep 8)
 
**Completion Deadline:** Sep. 5
 
# **Documentation** (to be DONE!!!!)
- [Development wiki page](../wiki/Day-and-Night-Cycle-Service)
- [JavaDoc](https://uqdeco2800.github.io/2022-studio-1/com/deco2800/game/services/DayNightCycleService.html)
 
# **Member**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
