### ISSUE TITLE
Shop Inventory + Memento expansion

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2022-studio-1#105]
# **Description**
**Task:** [Shop Inventory + Memento expansion](#105).
**Feature:** [Shop Extended Functionality](#94)

In this sprint, the shop will be expanded, introducing items for players to buy and use, as player buys an item, storing it will also be required, to cope with the expansion, it is necessary that the inventory and memento is also expanded to "store" the items.

The player states will also need to be adjusted upon purchasing, memento will also need to be able to detect and store these changes
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] introduce new data structures to store different item types
- [x] link data structure to inventory and shop
- [x] change memento according to track the items
- [x] Junit tests implementation
 
**Completion Deadline:** Sep. 11

# **Extra**
- [x] change the memento design pattern to make it work more efficiently

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@Lumin-cider) (Cheng-Yu Lin)
