### ISSUE TITLE
S2-Team-6-Shop-Screen-Edits

### ISSUE THREAD

**Issue by venndiagram5** [UQdeco2800/2022-studio-1#106]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Shop Extended Functionality] (#94)

Now that the shop exists from Sprint 1. There is some additional visual changes that are to be made. The carousel in the shop needs to be improved to show the items on the left and right of the current item as well as an indicator showing the current item number out of the total number of items. The items in the shop will also be move to objects created from a JSON to reduce the need for too many class files. This will allow very quick addition of new items by just specifying it in the json file and running it through a factory constructor pattern. Lastly som visual and audio changes will be made to the shop for when buttons are pressed and events occur like buying an item or navigating next on the carousel.

# **Dependencies**
- [ ] Sounds and animation from UI/UX sub team
- [ ] New items for shop from the team and studio class
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement JSON factory constructor (Sep. 7)
- [ ] Implement changes to shop screen layout and design (Sep. 8)
- [ ] Add new items to store (Sep 9.)
- [ ] Create unit tests and front end testing (Sep. 12)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Shop Wiki](https://github.com/UQdeco2800/2022-studio-1/wiki/Shop)
 
# **Member**
- Satya Bhasale (@venndiagram5 ) (Satya Bhasale)
