### ISSUE TITLE
Melee Enemy Pathfinding

### ISSUE THREAD

**Issue by MichelleAsWell** [UQdeco2800/2022-studio-1#108]
# **Description**
**Task:** Melee Enemy Pathfinding.
**Feature:** [Melee Enemy Improvements](#107)

Melee Enemies should attack the crystal in the centre of the map. They should move towards the enemy, stop when they encounter obstacles and, if the obstacle is not destroyable, should attempt to find their way around it. Enemies should appear to face the direction they are moving.

# **Dependencies**
- [ ] Existence of melee enemies (#3)
- [ ] Creation of directional sprites

# **Milestones**
List of steps that need to be completed for this task.
- [ ] (Sep. 08) Pathfinding algorithm written
- [ ] (Sep. 09) Pathfinding testing completed
- [ ] (Sep. 09) Directional sprites implemented
- [ ] (Sep. 11) Directional sprite testing completed
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- TBC
 
# **Member**
- Michelle (@MichelleAsWell) (Michelle Sands)

**Comment by MichelleAsWell** [comment]
Note that a quick conversation with team 7 today (studio session 7/9/22) confirmed that all buildings will be attackable & destroyable by enemies, which will simplify the algorithm - less avoidance required

**Comment by MichelleAsWell** [comment]
I went a little overboard with this one and tried to implement a repeated attack task, which has caused a lot of problems & wasted a fair amount of time. Note that this (having melee enemies attack more than once) might be worth implementing for the next sprint
