### ISSUE TITLE
StoryLine Cutscenes

### ISSUE THREAD

**Issue by 4vir4l** [UQdeco2800/2022-studio-1#109]
# **Description**
For the Sprint 2, Team 2 will work primarily on the game’s storyline. This includes creating the design for the cutscenes animations and implementing it into the source code.
These cutscenes will be played on full screen with audio for full immersion.
We will follow the design guidelines to stay in sync with the current UI and gameplay.
Our goal is to invest the player emotionally into the game. 

## SubFeature/component with example
Prologue: Would give the player a story of Atlantis. This would give context to how Atlantis used to be, what happened, why the crystal matters and how the main char came to be.

Night scenes: These would be played before [each night or only on the last/boss night] so as to provide a transition to the enemy wave and also introduce a new enemy character and its strengths.

Crystal upgrades: A cutscene that plays on every crystal upgrade.

Epilogue: This would only play if the player wins. This may be an exaggerated celebration and the future prosperity of Atlantis.
Skip button: A skip button for all cutscenes.

# **Dependencies**

Win and Lose conditions must be implemented before the end cutscenes can be used.
Boss must be confirmed and designed before boss night cutscenes could be made.
Crystal upgrade must be functional for the cutscene to be used.
Audios must be available for each cutscene.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 0 (Sep. 3)
	- [ ] Confirm with Team 1 and Team 5 if the enemy boss will be implemented in the game.
	- [ ] Discuss with Team 8 if the crystal upgrade cutscene can be implemented.
	- [ ] Discuss with Team 9 if the Day and Night cycle will be an instant or dynamic transition.
	- [ ] Discuss with Team 11 if they can work with us in Sprint 2 to create audio tracks for cutscenes.
- [ ] Goal 1 (Sep. 5)
        - [ ] Prologue Story written
- [ ] Goal 2 (Sep. 7)
	- [ ] Design drafts for the prologue [paper]
	- [ ] Design drafts for the crystal upgrade [paper]
	- [ ] Design drafts for the boss enemy [paper]
	- [ ] Design draft for the Epilogue [paper]
- [ ] Goal 3.1 (Sep. 10)
	- [ ] Design ready for the crystal upgrade
        - [ ] Design ready for the Prologue
- [ ] Goal 3.2 (Sep. 11)
        - [ ] Design ready for the Epilogue
        - [ ] Design for the boss character
- [ ] Goal 4 (Sep 13)
	- [ ] Cutscene animations implemented in the game.
	- [ ] Skip button added to the animations.

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Add a tutorial screen: This may be a 1 screen page that may describe the controls and what individual entity / interactable elements means in the game.
- [ ] Disable cutscenes: Clearly described to the studio on how to disable cutscenes in the code base so individual branches can test their features efficiently.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Viktor Milanov (viktormmilanov) (Viktor Milanov)
- Rafe Klein (rafe171) (Rafe Klein)
- Rohan Teotia (RohanTeo) (Rohan Teotia)
- Suhas Udupa (suhasudupaa)(Suhas Udupa)
- Aviral Sharma (4vir4l) (4vir4l)

**Comment by a-siroki** [comment]
Updating the final boss sketch and high fidelity design for reference in relation to the main storyline! Thanks guys!!
![low-fidelity-sketch-final-boss-west-direction](https://user-images.githubusercontent.com/109805074/189785407-761b23f0-457f-4e2a-92dc-5082561ee849.jpg)


![boss_enemy_angle1](https://user-images.githubusercontent.com/109805074/189785380-5f3ede72-fa84-4f6a-bf4d-6e929476ce21.png)
