### ISSUE TITLE
Day and Night Clock Design

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#110]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Day & Night Cycle](#101)

The task ticket regards the design of the day and night clock which will visually convey to the user which cycle they are in: Dawn, Day, Dusk, Night. 

# **Dependencies**
- [x] Day and Night Timer (#102)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Research & Sketch Draft Clock Designs (Sep. 6)
- [x] Create Initial Sprites (Sep. 7)
- [x] User Testing Survey (Sep. 11)
- [x] User Testing Paper Prototype (Sep.10)
- [x] Finalise Sprites (Sep. 12)
- [x] Implement Sprites (Sep. 12)
- [x] Wiki Documentation Design Inspiration & Ideation
- [x] Wiki Documentation User Testing
- [x] Unit Testing (Sep. 10)
 
**Completion Deadline:** Sep. 13
 
# **Documentation** 
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Samantha Smart (@samsmarttt) (samsmartt)

**Comment by samsmarttt** [comment]
[7/09/2022] Team collaboration occured with team 3 (terrain) during the studio, the initital prototype of the clock was showcased to which feedback was recieved regarding the design. Further, we (team 9) provided feedback regarding the terrian and their desire and proposal of changing the terrain from grass to sand. 
This meeting also allowed for our team to realise that not necessarily all teams would want the shader to be applied to their game element. Team 3 expressed that they wanted to create their own night time tiles - glowing water. The team thought their ideas were really good.
