### ISSUE TITLE
Ranged Enemy AI 

### ISSUE THREAD

**Issue by Josephjmet** [UQdeco2800/2022-studio-1#113]
# **Description**
Ranged Enemies should attack the crystal in the centre of the world, but do so at a range. They should move towards the enemy when in range, but when they are not continue to target the crystal, stop when they encounter obstacles and, if the obstacle is not destroyable, should attempt to find their way around it. (Ai Tasks)

Enemies should appear to face the direction they are moving. (Animation)

# **Dependencies**

- Creation of a static map

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Improve pathfinding for AI to target crystal (Sep. 3)
- [ ] Improve pathfinding for AI to stay at range  (Sep. 3)
- [ ] animation of sprite: sprite direction (Sep. 7)
- [ ] Obstacle Pathfinding (Sep. 7)
- [ ] Goal 4 (Aug. 28)

**Completion Deadline:**  Sep. 14

# **Documentation**

# **Members**
- Joseph (@Josephjmet ) 
- Heather (@hblakeway)
- Lung-Yu (@LungYuLin )
- Yuhang (@1023790021 )
- Aman (@aman-86)
