### ISSUE TITLE
Map Borders and New Map Generation

### ISSUE THREAD

**Issue by Xodacan** [UQdeco2800/2022-studio-1#114]
# **Description**
Sprint 2 requires implementation of proof of concept for levels as decided by Studio 1. Team 3 will continue working on the map development for sprint 2, rectifying the island borders feature from sprint 1, resizing the tile, facilitating the change of graphical art with day-night cycle and implementing the increase of payable space in the island for the user.

## SubFeature/component (optional)
>	Fixing the borders for the island
>	Resizing/scaling the tiles and the other items on the map
>	Facilitating the graphic design for day/night cycle
>	Implementing the increase of playable land 

# **Dependencies**
Add any if required 

# **Milestones**

- [ ] 	Static map discussion – team 5 and 8 (on Sept 7th)
- [ ] 	Tile size scaling (Sept 6th)
- [ ] 	Fixing the borders (Sept 7th)
- [ ] 	Day/night cycle artwork swap (Sept 9th)
- [ ] 	Increasing playable land (Sept 11th)
- [ ]  Junit/Testing ( Sept 13th)

**Completion Deadline:** Sept 13th

# **Members**
- sam (GitHub Username) (Slack Handle) 
- tayla(GitHub Username) (Slack Handle)
