### ISSUE TITLE
Map Design (Graphic)

### ISSUE THREAD

**Issue by Xodacan** [UQdeco2800/2022-studio-1#115]
# **Description**
Sprint 2 involves team 3 having to add variety to the map’s terrain. New tile designs and art rework.

## SubFeature/component (optional)
>	Water tile rework
>	Day/night tile rework
>	Design Small Elements on the sand
>	Design Cliffs -> beach
>	Design Stone tile, sand tile
>      Change Trees into Shipwrecks

# **Dependencies**

Add if any
e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x]  Research and feedback (Sept 5th)
- [x]  Static map discussion – team 5 and 8 (on Sept 7th)
- [x]	Decide on the tile size (Sept 6th)
- [x]	Design first version of artwork  (Sept 8th)
- [x] Design shipwreck (Sept 8th)
- [x]	Receive feedback (Sept 9th)
- [x]	Reconfigure the designs on the feedback (Sept 11th)
- [ ]	Testing (Sept 13th)
- [ ] Wiki writing (Sept 13th)

**Completion Deadline:** Sept 13th

# **Members**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
- Emily (GitHub Username) (Slack Handle)
- Pragun Ramesha (Xodacan)
