### ISSUE TITLE
Design boss enemy character

### ISSUE THREAD

**Issue by Annabel-Kennedy** [UQdeco2800/2022-studio-1#122]
# **Description**
**Task:** [Design boss enemy character]()
**Feature:** [Melee Enemy Improvement](#107)

A new enemy boss character will be designed for this task with at least 4 different sprites and, if time permits, animation.

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Conduct user testing to understand users' expectations for the appearance and movement of the boss enemy character (Tue Sep. 6) 
- [ ] Create isometric sketches of potential boss characters based off user research (Wed Sep 7.) 
- [ ] Complete min. 4 sprites of final boss in pixilart.com, following object design guidelines (Sun Sep. 11)
- [ ] User feedback on final pixilart boss enemy character (Sun Sep. 11)
- [ ] Finalise boss enemy character by incorporating user feedback (Mon Sep. 12)
- [x] Incorporate boss enemy character into game (Mon Sep 12.)
 
**Completion Deadline:** Mon Sep 12.
 
# **Documentation**
- TODO [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Annabel (@Annabel-Kennedy) (Annabel Kennedy)
- Aleks (@a-siroki) (Aleks Siroki)
