### ISSUE TITLE
Implementation of Melee Boss

### ISSUE THREAD

**Issue by Logan-De-Groot** [UQdeco2800/2022-studio-1#123]
# **Description**
**Task:** Implementation of Melee Boss Enemy
**Feature:** Melee Enemy Improvement #107

The goal is to have a Melee boss enemy that will soley target the crystal providing a challenge to the player. This boss will deal additional damage to walls allowing it to get to the crystal quickly and will have an increase to HP and damage. This enemy will spawn during the night on the final night or potentially at key moments to further threaten the player. It will require a path finding algorithim and various components.

This boss also has the additional extra depending on timeframes to apply affects such as a speed increase to enemies near by.

# **Dependencies**
- As the enemy will target structures it is dependent on #53 and #25 for positioning infomation
- This is a futher extension of #57, Melee Enemy Design
 - Spawning of enemies and night time cycle #101 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - Base class designed and implemented by 7/09
- [ ] Step 2 - Algorithim and AI designed to Target Crystal by 11/09
- [ ] Step 3 - Additional Affects if time permits and bug fixes  12/09
 
**Completion Deadline:** Sep. 13

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Logan De Groot (Logan-De-Groot)(IAmGroot)
