### ISSUE TITLE
Addition of day-night-cycle shader

### ISSUE THREAD

**Issue by cholnhial** [UQdeco2800/2022-studio-1#128]
# **Description**
**Task:** [Addition of day-night-cycle shader](#3).
**Feature:** [Feature which this tasks contributes to implementing](#101)

This task is for the addition of a day-night-cycle shader that will give the resemblance of dawn,day,dusk and night in the game look. When an event is received for each of the transitions between the parts of day, the shader will shade the game area accordingly. The shader should not be shown when the menu screen is up or any other screens in that regard. It should only be shown for the game screen.

NOTE: there will be some limitations in getting the filter to not darken menu buttons etc. 

# **Dependencies**

- [x] Day Night Cyce Service (aka Timer) 102 (#102)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Allow shader to listen to events and respond (Sep. 5)
- [x] Avoid shading menus  (Sep. 5)
- [x] Add in between day and night (Sep. 5)
- [x] Fix ups and getting intensitites to display correctly (Sep. 8)
 
**Completion Deadline:** Sep. 12

 
# **Documentation (ADD DOCUMENTATION)** 
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)

**Comment by samsmarttt** [comment]
[07/09/2022) The studio class allowed for our team to realise that not necessarily all teams would want the shader to be applied to their game element. Team 3 (@taylaward) expressed that they wanted to create their own night time tiles - glowing water. The team thought their ideas were really good! Further team 1 (@hblakeway) was happy to have their characters shaded.

**Comment by cholnhial** [comment]
Team8 would like to have the shader not shade the crystal as they will add some of their effects.
