### ISSUE TITLE
MAIN CHARACTER - Design and Basic Behaviour

### ISSUE THREAD

**Issue by 4vir4l** [UQdeco2800/2022-studio-1#13]
# **Description**

Team 2 will be implementing the design and basic behavioral characteristics of the main character and the citizens. The main character's goal is to protect the crystal and fend off enemies. It will have the different abilities to attack the enemies based on the character chosen or the upgrades. On the design side of this feature, we would be involved in creating the design of the player (main character), health bar (on the player) and the combat design (main character with a weapon). We would be programming to incorporate the above designs into the game and implement the features of movement, decreasing player health and ability to combat (eg. melee).

### Main character design 
Visual appearance of the main character who is going to be a ‘Chief’ like character for Atlantis throughout the game.

### Movement 
This would be the 8 - directional movement that the user would be able to control. This subfeature would be essential for future sprints for areas like Interaction with NPCs, Attack/ Defense.

### Player Health
This will display the main character’s health. The health bar will have dynamic movement fixed to the main character’s position.

### Combat
This feature allows the main character to attack enemies during night time with a weapon selected as well as damage statistics, this feature would also have a weapon (eg. sword) in their hand with multiple frame animations for an attack (eg. melee).
The main character will default to attacking enemies in range unless directed otherwise. 

Visual Health - update character look based on remaining health (Extra)

# **Dependencies**

- Enemies have to spawn and attack the main character.
- Health of the main character depends upon the type of damage received from the enemies.
- The amount of health the main character has depends on the level of the game and the character chosen.
- The type of attack performed by the main character depends on which weapons have been equipped.
- Movement of character depends upon the building grid system of the map and the placement of the buildings.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 Design finalization for the main character (Aug. 20)
- [ ] Goal 2 Movement of character in 8 directions and correct sprite shown (Aug. 23)
- [ ] Goal 3 Health system (health bar) (Aug. 26)
- [ ] Goal 4 Combat with frame designs of the main character with a weapon (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extra**

### Main Character selection

Different main characters will have different special abilities i.e., high HP, long range attack or short range attack, faster movement, etc.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**

- Viktor Milanov (viktormmilanov) (Viktor Milanov)
- Rafe Klein (rafe171) (Rafe Klein)
- Rohan Teotia (RohanTeo) (Rohan Teotia)
- Suhas Udupa (suhasudupaa)(Suhas Udupa)
- Aviral Sharma (4vir4l) (4vir4l)

**Comment by luke4641942** [comment]
Just a quick revision about what we (team 5) discussed with you guys in the studio on Wednesday. We spoke about how the main character can potentially mine the blocks and gain resources from them early game. Some simple mechanic that if you press space bar over the block, the block becomes grass (buildings can then be built on it) and then the resources appear in a counter next to gold at the top of the screen (for example). Intend to check in next week about how we're all going and if plans are still feasible (as this will probably be labelled as an extra in your ticket).

**Comment by luke4641942** [comment]
Just a quick revision about what we (team 5) discussed with you guys in the studio on Wednesday. We spoke about how our team would be implementing the main character mining the stones and trees on the map to gain resources in the early game. We also spoke about how our team was going to add the multidirectional sprites as per the moment direction that you had already finished just didn't get around to implementing.
