### ISSUE TITLE
Shop-Equipment-page

### ISSUE THREAD

**Issue by Tianyuanhaimo** [UQdeco2800/2022-studio-1#137]
# **Description**
**Task:** Equipment page
**Feature:** [Shop Extended Functionality](#94)

In sprint 2, the store interface will add equipment button, users can open the equipment page by clicking the equipment button, to buy equipment operation.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add Equipment button (Sep. 5)
- [ ] Add Equipment page (Sep. 6)
- [ ] Implementing the equipment page item framework (Sep. 7)
- [ ] Link the button to the store page (Sep. 8)
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Yi Yang (@Tianyuanhaimo ) (Yi Yang)
