### ISSUE TITLE
Recreating main tiles

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#138]
# **Description**
**Task:** [Recreating main tiles](#3).
**Feature:** [Map Design (Graphic)](#115)

During our discord meeting, there was a change in the map theme. Since it is an Atlantis theme, we shall swap the grass for sand and sea plants(ex. seaweed and coral). Also, changed from cliff to beach. Therefore, team 3 will be designing  new major tiles at this task.
 
# **Dependencies**

- [ ]  Map Boarders and New Map Generation (#114)
- [ ] Design pixel art for blocks (detailed style) (#37 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Sketch prototype of tiles needed (Sept 6th)
- [ ] Create the first version (Sept 8th)
- [ ] Modify according to feedback (Sept 11th)
- [ ] Retrieve feedback (Sept 12th)
- [ ] Modify according to feedback (Sept 13th)
- [ ] Testing (Sept 13th)
 
**Completion Deadline:** Sept. 13
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
-Emily (GitHub Username) (Slack Handle)
-Pragun Ramesha (Xodacan)
