### ISSUE TITLE
Ranged Enemy Creation

### ISSUE THREAD

**Issue by 1023790021** [UQdeco2800/2022-studio-1#14]
# **Description**
Enemies are an indispensable entity in every tower defence game, and whether the player successfully defend the enemies is the win condition of this game. The enemies in this game are mainly divided into two attack modes: melee attacks and long-range attacks. Enemies in melee attack mode will attack with special melee weapons and other melee attack ways, while enemies in long-range attack mode will attack with long-range weapons, magic, and other special long-range. Enemies that combine two attack modes (melee and long-range) and various bosses will spawned in specific levels. The main targets of enemy attack in descending order are: defence towers -> player -> crystal, and when player is outside the range of defence towers, player will also receive enemy attacks. Additionally, enemies will only spawn at night, while the level of the enemy will increase as the level of the level increases. Finally, the game will end in defeat if an enemy attack succeeds in draining the crystal to 0 health points.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**
- Working with team 9 (melee enemy team) to ensure art style and movement is consistent
- Working with team 2 (main character team) to ensure art style is consistent
- Working with team 7 and 8 (crystal and building team) to ensure damage and health is consistent
- (#75)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create preliminary design for enemy sprites (Aug. 20)
- [x] Finalise low fidelity design for enemy with studio feedback (Aug. 24)
- [x] Ensuring enemy design is consistent w/Team 9 (Aug 25)
- [x] Finalise medium fidelity design, with 4 facing directions (Aug 26)
- [x] Enemy entity created and visual on the map (Aug 24)
- [x] Movement on map towards a target (Aug. 28)
- [x] Documentation of enemy creation (Aug.28)
- [x] Basic damage and updating enemy with AI values: longer range of chase (Aug. 30)
- [x] groundwork for sprint 2: creating basic entity for projectile to integrate with ranged enemy (Aug. 30 ->)

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Ranged-Enemies)

# **Members**
- Aman Gupta
- Heather Blakeway
- Joseph Metcalfe
- Lung-Yu Lin
- Yuhang Lin
