### ISSUE TITLE
Tile Design

### ISSUE THREAD

**Issue by Xodacan** [UQdeco2800/2022-studio-1#140]
# **Description**
**Task:** [Tile Design](#3).
**Feature:** [Map Design](#2)

The design in the first sprint lacked intricate details on the map. Hence team 3 is redesigning the water tiles and landscape tiles based on the research done for sprint 1 (This could not be implemented in sprint 1 due to late responses for the surveys). 
 This includes different tiles for water, sand, stone, sand with seaweed etc.

# **Dependencies**
- [ ] Tile size must be known
- [ ] Research from first sprint 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design first version of tiles (Sept 7th)
- [ ] Feedback from users  (Sept 9th)
- [ ] Apply the feedback in a new version of the tiles (Sept 11th)
 
**Completion Deadline:** Sept 11th
 
# **Member**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
-Emily (GitHub Username) (Slack Handle)
-Pragun Ramesha (Xodacan)
