### ISSUE TITLE
Spawning Melee Enemies During Gameplay

### ISSUE THREAD

**Issue by setoaprasetyo** [UQdeco2800/2022-studio-1#143]
# **Description**
**Task:** Spawning Melee Enemies During Gameplay
**Feature:** [Melee Enemy Improvement](#107)

The goal is to have enemies spawning at the edges of the map at the time night arrives. The spawning enemies will come from every side of the map surrounding the player and the crystal

# **Dependencies**
- [ ] This is a futher extension of Melee Enemy Design (#57)
- [ ] Melee Enemy Improvement (#107)
- [ ] Night Time Cycle (#101)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - enemies able to spawn at night (07/09)
- [ ] Step 2 - enemies spawn along the edges of the map (08/09)
- [ ] Step 3 - (optional) enemies are able to spawn from the water and walk towards land (10/09)
 
**Completion Deadline:** 12/09
 
# **Documentation**
- Wiki: [Melee Enemies](https://github.com/UQdeco2800/2022-studio-1/wiki/Melee-Enemies)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Seto (@setoaprasetyo) (Seto Adhi Prasetyo)

**Comment by MichelleAsWell** [comment]
Just commenting here to formalise a quick discussion we had with the programmers of team 7 (for posterity / sprint achievement form) - we'll need to make sure spawned enemies are registered with the EntityService so buildings can target them!

**Comment by setoaprasetyo** [comment]
We had collaboration with team 3 so that the spawning position of the enemies are set on a ring surrounding the land; on the water spawnable tiles.
