### ISSUE TITLE
Wood Resource Building 

### ISSUE THREAD

**Issue by sukizzz** [UQdeco2800/2022-studio-1#144]
# **Description**
**Task:** [Wood Resource Building](#144).
**Feature:** [Resource Management (Including Resource Buildings)](#11)

This task will require us (team 5) to implement our second resource generation building in the Wood Refinery Building. This building is not dissimilar to the Stone Quarry where it generates resources based on the level of the game and is bought as an investment to generate more wood that can be spent in the future. For this task we will be required to go through idea generation of a new building, create a pixel version and finally implement into the game.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete designs and ideation (Sep. 5)
- [x] Have all Low and High Fidelity drawings completed (Sep. 7)
- [x] Implement it into the game (Sep. 10)
- [x] Make sure the code functionality works (Sep. 12)
 
**Completion Deadline:** Sep. 13

# **Extras**
- [x] Add animation to the wood generator 
- [x] Move from levels based to time based 

# **Documentation**
- [Resource Management wiki page](https://github.com/UQdeco2800/2022-studio-1/wiki/Resource-Management)
 
# **Member**
- Luke Graham (@luke4641942) (Luke Graham)
- Cliff Worsfold (@JumpOffACliffy) (Cliff Worsfold)
- Suki Zhang (@sukizzz) (Suki Zhang)
- Xi Wang (@XiWangBeryl) (Xi Wang)
- Naman Agarwal (@Naman-Agarwal1608) (Naman Agarwal)
