### ISSUE TITLE
Design environmental and artificial objects for terrain

### ISSUE THREAD

**Issue by Annabel-Kennedy** [UQdeco2800/2022-studio-1#15]
# **Description**
**Task:** [Design basic environmental and artificial objects for both land and ocean](#3).
**Feature:** [Landscape Objects](#2)

4 types of objects will be designed for this feature: environmental objects for land; artificial objects for land; artificial objects for ocean; and artifacts. The specific objects that will be created for each type are:

| Object type			| Objects to be created		|
| —---------------------------------- | —-------------------------------------------- |
| Environmental land objects  | Tree, forest patch, rocks/boulders, cobwebs |
| Artificial land objects | Smart digital street map with emergency warning |
| Objects for ocean | Floating raft, a shipwreck, parts of a ship wreckage, fishing boat |
| Artifacts/powerups | Ancient greek coin, futuristic laser weapon, ancient greek helmet, mermaid |

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Research/learn how to create isometric detailed pixel art using Adobe (Fri Aug. 19)
- [ ] Sketch, compare and finalise designs for environmental land objects (Sat Aug. 20) 
- [ ] Create environmental land objects in Adobe (Mon Aug. 22)
- [ ] Sketch, compare and finalise designs for artificial land objects and objects for ocean (Tue Aug. 23)
- [ ] Create artificial land objects and objects for ocean in Adobe (Thu Aug. 25)
- [ ] Sketch, compare and finalise designs for artifacts/powerups (Fri Aug. 26)
- [ ] Create artifact/powerup objects in Adobe (Mon Aug. 29)
 
**Completion Deadline:** Mon Aug. 29
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Annabel (@Annabel-Kennedy) (Annabel Kennedy)
- Aleks (@a-siroki) (Aleks Siroki)

**Comment by Annabel-Kennedy** [comment]
Discussions with the design committee on discord (@a-siroki taking lead) and other teams in the studio session today (team 10, 5 and 3) confirmed that the following art style and measurements will be used in our high-fidelity designs: 1 pixel black borders, create our objects exactly to scale, use 30 degree perspective

**Comment by a-siroki** [comment]
It has been finalized and all teams should be using a correct 30 degree tile now. We also updated the Design Guidelines. Thanks @Annabel-Kennedy 
![discord 2](https://user-images.githubusercontent.com/109805074/187113108-618d7d86-e89c-4419-ba8a-a9773749eb9d.JPG)
![discord 1](https://user-images.githubusercontent.com/109805074/187113117-79443500-2624-4e3f-b62e-efb86c252fcd.JPG)

**Comment by Annabel-Kennedy** [comment]
A discussion with designer from team 7 on 25/08, confirmed that the design guidelines for objects will include dark coloured borders, as opposed to previously mentioned black borders.
![image](https://user-images.githubusercontent.com/83194467/187221627-2b3ae85a-7eda-45ce-acf2-6cfef756db70.png)
