### ISSUE TITLE
Implement User-Interface (UI)

### ISSUE THREAD

**Issue by ChevScore** [UQdeco2800/2022-studio-1#16]
# **Description**
Team ten was assigned the User Interface (UI) feature ticket and intends to deliver a multitude of essential overlays, pop ups and menus to enable game functionality and interactivity. UI is fundamental to the game and must be intuitive and pleasant for the end user to ensure smooth interactions with the system. This UI functionality should be stand alone and not depend on the game mechanics, and rather be inherited. The UI that is going to be created has to be intuitive so that users would understand the purpose for each UI with ease. The UI components should be generic enough to be implemented by any game, but specific enough to incorporate most (or all) of the aspects/features of the game (e.g genre, colours).

## SubFeature/component (optional)

- Menu - A start menu to invite the user to start the game. 
- Inventory  - displaying a simple pop that shows the user what they have collected or artifacts. 
- Settings Page - the settings page will be an interactive page that holds settings for music, save options, and exiting the game.  
- Entity Statistics - information holder, that shows the user the statistics of the enemies. A tooltip for the user to evaluate the enemy. 
- Hints and Prompts - game tutorial, a pop-up that can easily be excited. 
- Achievement pop-ups - win or lose messages 
- Game Page - Layout of stats, game screen
- Buttons - Designing the theme of the button but functionality of the button is the main aim.
- User Testing - Help determine if the interface is easy to navigate and intuitive. 

## **Examples (optional)**
Below is an example of different widgets/ buttons that our team would like to create and has been described above. 
[https://interfaceingame.com/games/clash-of-clans/ ](url) 

# **Milestones**
- Goal 1 (Aug. 20):
- [ ] Symbols and icons 
- [ ] Button tile design for all pages - general layout/shape/colour
- [ ] Write hint/prompt and generic text 
- Goal 2 (Aug. 23): 
- [ ] Making the layout of the screens (Menu page, Game Page, Entity Statistics)
- [ ] Sorting button layout, with the buttons still static
- [ ] Start-up screen customization 
- [ ] Style of additional pages, such start and setting pages
- Goal 3 (Aug. 26): 
- [ ] Linking pages with event handlers 
- [ ] Talking to other dependent teams to see what else we can link together with our work.
- [ ] Making the hint and prompt pop-ups appear when clicked.
- [ ] Making achievement pop-ups appear 
- [ ] Work with the other teams to link the buttons of the settings
- Goal 4 (Aug. 28): 
- [ ] Testing - functional testing, making sure there are no issues with links or button functionality. 
- [ ] Final objects connected and finalized integration. 

**Completion Deadline:** Aug. 30

# **Extras (optional)**
Inventory - an inventory pop-up, to interact with the artifacts collected. 
Store - an interactive store page and layout.

# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)

**Comment by mackenziekerr1** [comment]
Hey Team 10, Just jumping in here to confirm that we will utilize your design guidelines to create the shop interface and will run this by you guys for approval towards the end of Sprint 1. Also double checking that you guys will provide the assets for the shop button and any typography for us to use?

**Comment by tgarnsworthy** [comment]
@mackenziekerr1 can confirm this. We have created a design guidelines document on google shared drive where you can access the uniform typography, UX goals and more anytime.

**Comment by tgarnsworthy** [comment]
Discussed with team 8, that we are going with #E0B0FF as the crystal colour.

**Comment by tgarnsworthy** [comment]
Consulted with all teams for the final wireframes for sprint 1. Main points: Two health status bars (one for main character health and one for crystal health). Secondly, two currency counters need to be implemented (coin counter and stone counter). Remove the attack button as it is not required. Potentially implement day and night indicators.
