### ISSUE TITLE
Enable UI components to accurately display crystal information (health)

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#164]
# **Description**
**Task:** [Enable UI components to accurately display crystal information (health/level)](#3).
**Feature:** [Upgradable Crystal Feature](#117 )

Integrate UI component on top left corner (currently an image) with the health bar of the crystal to ensure it accurately displays health value of the crystal. Ensure overall aesthetic of game is maintained throughout this process.
 

# **Dependencies**

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep. 7) Add a label to display numerical value of crystal health 
- [ ] Step 2 (Sep. 8) Position crystal health bar on top left corner alongside other player stats
- [ ] Step 3 (Sep. 9) Customize health bar design and incorporate original health bar image to match aesthetic of game 
 
**Completion Deadline:** Sep. 9

 
# **Documentation**
- [Crystal Feature](../wiki/Crystal-Managment)

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
