### ISSUE TITLE
Enable Crystal texture to be changed with each upgrade

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#165]
# **Description**
**Task:** [Enable Crystal texture to be changed with each upgrade](#3).
**Feature:** [Upgradable Crystal Feature](#117 )

Apply newly-designed textures to the crystal to enhance the look of the crystal with each upgrade of level.
 

# **Dependencies**
- [ ] Dependency 1 
Dependent on designers to design new look of Crystal for each level
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 9) Develop function to spawn crystal outside of game area
- [x] Step 2 (Sep. 10) Modify original upgrade function to spawn crystal with new texture when upgraded
- [x] Step 3 (Sep. 11) Develop function to trigger upgrade function when crystal is clicked (this will be integrated with a small pop up similar to building UI in future sprints
 
**Completion Deadline:** Sep. 11

 
# **Documentation**
- [Crystal Feature](../wiki/Crystal-Managment)

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
