### ISSUE TITLE
    Implement functionality to restore lost crystal health 

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#183]
# **Description**
**Task:** [Implement functionality to restore lost crystal health ](#3).
**Feature:** [Upgradable Crystal Feature](#117 )

User testing to be conducted to determine the most suitable method to restore crystal health. Options include :
1. Crystal slowly restores health through time (during the day)
2. Crystal restores health only when upgraded
3. Crystal restores health by players buying "potions" from shop
 

# **Dependencies**
- [ ] Dependency 1 
Dependent on User Testing result
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 7) Conduct user testing to determine method to implement (option 1 chosen)
- [x] Step 2 (Sep. 11) Set up timer to keep track of time and phase of the day 
- [x] Step 3 (Sep. 12) Create function in crystal factory to increase health of crystal through time 
 
**Completion Deadline:** Sep. 12

 
# **Documentation**
- [Crystal Feature](../wiki/Crystal-Managment)

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
