### ISSUE TITLE
Guide Book Implementation

### ISSUE THREAD

**Issue by ChevScore** [UQdeco2800/2022-studio-1#207]
# **Description**
The purpose of the guide book is to inform users of the game, its goals, controls, mechanics, in an aesthetically pleasing way. For goals, the guide book will briefly describe what the end goal is as well as some of the different aspects of the game. The controls and game mechanics 'page' will inform users on how to play the game, specifically what key binds exist and what movement controls are there. 

## SubFeature/component (optional)
Goal 1 ()
- [ ] Wire-frames development
- [ ] Icon & Asset Designs
- [ ] Creation of GuideBook class and set-up of the GUI Table
- [ ] User Testing on existing game
Goal 2 ()
- [ ] Placement of Assets on GuideBook
- [ ] Making GuideBook pop-up on button click and toggle visibility
- [ ] Develop different pages for the GuideBook
Goal 3
- [ ] Development of hints, tutorials & goals
- [ ] Development of GuideBook pages

Goal 4 ()

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Aug. 20)
- [ ] Goal 2 (Aug. 23)
- [ ] Goal 3 (Aug. 26)
- [ ] Goal 4 (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by jonooallen** [comment]
How will the user access the guidebook? Are you guys thinking a key-bind would be best?

**Comment by ChevScore** [comment]
@jonooallen we are thinking that since the guide book will explain all the keybinds in the game, it will be accessed through a button click that appears on the main game screen

**Comment by jonooallen** [comment]
Yeah that makes sense. Will the user be able to access it while the game is being played or only ever through main game screen.

**Comment by ChevScore** [comment]
@jonooallen it should be accessible through the main game screen while the game is being played. It would be, like the shop or settings page, a full screen like pop-up that temporarily pauses the game

**Comment by jonooallen** [comment]
Oh I see yeah that sounds good. 
Structures should need no key binds pending building UI and Shop integrating their code into the game.
Unified Grid System should also not need keybinds as it is a backend service.

**Comment by luke4641942** [comment]
Just for note, we spoke at the studio on Wednesday about what should be put in the wiki in terms of Main Character Features and Resource Buildings and were previously implemented by us (team5).
