### ISSUE TITLE
Unified Grid System

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#208]
# **Description**
The team intends on creating and implementing a unified grid system for use across the whole studio. This collision matrix involves recording the state of every tile in the game *?, as well as the location of all entities in the game ?.* This feature is important to the studio as a whole as it adds a method of obtaining the state of tiles which will be used by the whole studio, which is an improvement over the current system where different teams are using their own systems which don't integrate together seamlessly. On starting the game, the grid system will be created and will then be updated every frame. 

# **Dependencies**
- [ ] Map integration
- [ ] Entity system integration

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Create grid system Sept. 23 
- [ ] Integrate with map team Sept. 25
- [ ] Integrate with enemies team Sept. 25

**Completion Deadline:** Oct. 4

# **Extras (optional)**
- [ ] 

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Harland Jensen (@harland-jensen) (Harry Jensen) 
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by alexyun0429** [comment]
Hi Team 7, as we spoke on Wednesday, could you finalise the size of tile suits for buildings?

**Comment by jonooallen** [comment]
@alexyun0429 64x64f please and thank you.

**Comment by jonooallen** [comment]
@alexyun0429 this has changed to 16fx16f btw.
