### ISSUE TITLE
Refine building designs

### ISSUE THREAD

**Issue by schmidem** [UQdeco2800/2022-studio-1#209]
# **CURRENTLY UNDER CONSTRUCTION**

# **Description**
This should be roughly a one paragraph description of the features / ideas on which your team plans to work. It should very briefly touch on why you think it should be in the game (e.g. "Adds an extra layer of depth to game play"). It should also describe how it will appear or be used in the final product (e.g. "On starting a level, the game will generate a random, procedurally-generated map").

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Revise all existing building designs + user testing (Sep. 25)
     - Undertake multiple revisions cycles if applicable
- [ ] Add animations to applicable structures + user testing (Oct. 1)
- [ ] Finalise all design and animations (Oct. 3)
- [ ] Create sprite atlas

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by jonooallen** [comment]
Will there be multiple versions of the same building to accommodate the visual aspect of a tower being upgraded?

**Comment by luke4641942** [comment]
Just for note, we spoke in the studio on Wednesday about what grid system we wanted to use for the range class and the further designs for the unified grid system.

**Comment by SamBehm** [comment]
As part of #238, buildings will sink/be destroyed when the shoreline advances over them. Is there a plan for an animation for the building sinking/collapsing when the water raises again?

**Comment by jonooallen** [comment]
@SamBehm no this was not in the works, but I will pass it onto our designers and get back to you.

**Comment by schmidem** [comment]
> Will there be multiple versions of the same building to accommodate the visual aspect of a tower being upgraded?

For the tower specifically, yes. The turret will also have an upgraded version but it will be more subtle. We could possibly do so with the town hall as well, I'll discuss this with Iris.

**Comment by SamBehm** [comment]
I'll be doing user testing this weekend, so I'll leave that up to feedback, but I'll let you know :)

**Comment by schmidem** [comment]
**21/9/2022:** In-person studio discussion with Team 2 on integrating building graphics into pre-game tutorials. The finalised list of buildings (to call from in repo for implementation) has been sent. The first design iteration for new structures (Tower2, Tower3, Tower4, TownHall) will be completed and sent on Sept 23rd to be used as placeholders. Once a design is finalised, Team 2 will be notified. _All final designs will be given before or by Oct. 1_ @viktormmilanov @rafe171 @RohanTeo @suhasudupaa @4vir4l
