### ISSUE TITLE
Save Game, Multiple Difficulties and Enemy Attack Improvements

### ISSUE THREAD

**Issue by Logan-De-Groot** [UQdeco2800/2022-studio-1#221]
# **Description**
This feature ticket aims to implement and improve the game in multiple different areas. It will introduce a save game and load game ability, multiple different difficulties and improve enemy attacks to be more stable and less glitchy.

A same game and load game functionality is desired to help the player/user stop the game and return to it as wanted. Currently there is no ability to do this which has the potential to cause undue frustration as the user must either leave the game open in a paused state, quit the game or actively lose the game. None of these are a valid solution to the player/user wanting to start a game but being unable to finish it in one sitting which implementing a save/load game would solve. This will be implemented by writing to files and reading from files as needed.

The second feature wanting to be implemented is multiple different difficulties for the game. Currently there is only 1 difficulty which has the potential to be too hard for new players and too easy for returning or experienced players. If the game is too hard then the player will not want to return due to the difficulty while if the game is too easy experienced players will quickly grow bored. Implementing multiple difficulties would help alleviate this issue and allows the game to be fun and accessible to all players regardless of experience. This will be implemented by allowing the user to select a difficulty on the main menu screen before loading the game.

The final improvement wanted is fixes to enemy attacks and adding/implementing attack animations for the boss. Currently enemies just bump into the player/structure to deal damage which is non immersive and is quite glitchy with some attacks registering while others do not. Improvements and bug fixes will be sought in this area with additional/remaining time being used to implement animations for boss attacks.

## SubFeature/component (optional)

- Save Game & Load Game functionality
- Enemy Animations and Attack Improvements
- Difficulty Levels added
- Design and User testing of animations and difficulty levels

Reliant on:

- Melee Enemies for Boss Animations and Attack Improvements  (#57) 
- Entities, Structures, Player, Buildings, Environmental Object, Map and most functionality for loading and saving game state

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Sep. 18) Project Scope and Initial Understanding Completed
- [ ] Goal 2 (Sep. 21) UI elements designed and implemented
- [ ] Goal 3 (Sep. 22) Setup of save game completed with most dependencies being written to the relevant files
- [ ] Goal 4 (Sep. 24) Enemy attacks and bugfixes completed
- [ ] Goal 5 (Sep. 28) Load game implemented and functional 
- [ ] Goal 6 (Sep. 30) Multiple difficulties completed with varied enemy spawns
- [ ] Goal 7 (Oct. 2)  Animations for boss attacks introduced if time permits

**Completion Deadline:** Oct. 2

# **Documentation**
- Wiki: [Game Difficulties](https://github.com/UQdeco2800/2022-studio-1/wiki/Difficulties)
- Wiki: [Save Game](https://github.com/UQdeco2800/2022-studio-1/wiki/Save-Game)
- Wiki: [Melee Enemies](https://github.com/UQdeco2800/2022-studio-1/wiki/Melee-Enemies)
 
# **Members**
- Michelle (@MichelleAsWell) (Michelle Sands)
- Aleks (@a-siroki) (Aleks Siroki)
- Seto (@setoaprasetyo) (Seto Adhi Prasetyo)
- Logan (@Logan-De-Groot)(Logan De Groot)
- Annabel (@Annabel-Kennedy)(Annabel Kennedy)

**Comment by jonooallen** [comment]
How will the multiple difficulties be implemented, or is it still up in the air? Will it primarily be a multiplier to everything or will every class have to check the difficulty selected and change accordingly?
