### ISSUE TITLE
Saving and Loading Game

### ISSUE THREAD

**Issue by Logan-De-Groot** [UQdeco2800/2022-studio-1#222]
# **Description**
**Task:** Saving and Loading Game
**Feature:** [Save Game, Multiple Difficulties and Enemy Attack Improvements](#221)

From feature ticket a save and load game is desired to reduce the frustration from the player/user and allowt hem to play part of a game. Currently there is no ability to do this which has the potential to cause undue frustration as the user must either leave the game open in a paused state, quit the game or actively lose the game. This feature will write to files the relevant information and on start up will load the game state.

# **Dependencies**
Pretty much everything including but not limited to:

- Structures
- Enemies
- Environmental Objects
- Map Layout
- Day/Night time
- Entities
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Sep. 18) Project Scope and Initial Understanding Completed
- [ ] Goal 2 (Sep. 22) Setup of save game completed with most dependencies being written to the relevant files
- [ ] Goal 3 (Sep. 28) Load game implemented and functional 
 
**Completion Deadline:** 30 September
 
# **Documentation**
- [Save Game, Multiple Difficulties and Enemy Attack Improvements](#221)
- Wiki: [Save Game](https://github.com/UQdeco2800/2022-studio-1/wiki/Save-Game)
- [JavaDoc](JavaDoc/Location/Package/Class) once completed
 
# **Member**
- Logan De Groot(Logan-De-Groot) (Logan-De-Groot)

**Comment by SamBehm** [comment]
hey guys! I'm from team 3 working on the map, just wanted to offer our part of the save state. In terms of the map tile layout, you can either save just the map level index (current island size), or you can save the tiledMap in its entirety with the map level index. The advantage of saving the tiledMap would be that it's ~probably~ faster to load back in, as you're just coping the data straight back into the structure. However, this would take up a lot of space; by saving just the map level index, you can regenerate the map without any consequences by using terrainFactory. Either way if you need any help with this part of the save state implementation, let us know!

**Comment by MichelleAsWell** [comment]
![image](https://user-images.githubusercontent.com/110008322/193740199-3dab77be-a3dd-41bb-b20a-2e311a73e4b6.png)

**Comment by MichelleAsWell** [comment]
Note that the tutors have agreed to mark this functionality based on [this commit](https://github.com/UQdeco2800/2022-studio-1/commit/fd91cd94759eaffaa5fc7c945275f1162064da97) which is the last time we updated the SaveGameTest file before it was broken by other teams
![image](https://user-images.githubusercontent.com/110008322/193749607-973eb50c-fb6b-44fb-9ff0-f16eb36a19ba.png)
