### ISSUE TITLE
Finish guidebook info and finalisation with other teams

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#223]

**Comment by tgarnsworthy** [comment]
# **Description**
The task is to have the wireframes made at the beginning of the sprint so the design team can get underway. The wireframes form the basis of the design as well as bring to light all functionality and components required to generate the final product. Three versions of low fidelity wireframes were produced and then user testing was done to uncover which design best appeals to users. A higher fidelity wireframe would be produced after the feedback from user testing. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

**Goal 1 (Sep 5)**
- [x] Have low-fidelity wireframe 1 constructed.
- [x] Have low-fidelity wireframe 2 constructed.
- [x] Have low-fidelity wireframe 3 constructed.
- [x] Complete user testing with three versions.

**Goal 2 (Sep 8)**
- [x] Draft the second round of wireframes based on feedback.
- [x] Make medium-high fidelity wireframes.

**Completion Deadline:** September 20


# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)

**Comment by tgarnsworthy** [comment]
After consulting with studio we received the following change log to our guidebook content draft:
CHANGE LOG:
Team 4: Updated the day and night cycle content. There are 4 days and 4-night cycles. 
Team 1: Added different types of enemies and changed italicised section in enemies. 
Team 5: Added building names and descriptions of how they work. 
Team 6 added a  lot of information to the shop section. 
Team 9 updated the achievements section + pirate crab enemy
Team 7 added information to the building's section
