### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#224]
# **Description**
The addition of an achievement system will aim to encourage experimentation and enhance game play by giving the player something to work towards during the completion of the main storyline. For the first milestone, the achievements will be focused upon the story mode of the game with the intention to add more infinite orientated achievenments down the road. The achievements will be saved across the different game play sessions, and will further be categorised: Resources, Upgrade, Building, Level Completion, Kills etc.

Upon the completion of an achievenment, a notification will appear briefly with the title and description of the achievement obtained. Users will be able to access the list of achievements through the main menu, further while in game mode acheivements may be reviewed via a modal popup! 

# **Dependencies**
The persistance of achievements accross game plays will depend upon the implementation of the save state (#xx)

# **Milestones Sprint 3**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create Achievement List (Sep. 18)
- [x] Achievement Design (Graphics & Data) (Sep. 20)
- [x] UI/ UX Interface Design (Sep. 21)
- [x] Feature Implementation (Sep. 28)
- [x] Testing (Sep. 29)
- [x] Documentation (Oct. 1)

# **Milestones Sprint 4**
- [x] Add 'must' have achievements (rest of stat achievements + non-stat) (Oct. 9)
- [x] Lock/tick achievement badge designs (Oct. 10) 
- [x] Implement active tab signifier (Oct. 12)
- [x] User Testing (Oct. 13)
- [x] Added all achievements (Oct. 13)
- [x] Change to Popup (Oct. 16)
- [x] Improve UI/UX Design (Oct. 17)
- [x] Progression bar on each category page (Oct. 17)
- [x] Achievement Summary Progression (Oct. 17)

## **Stretch Goals**
- Notifcation popup pizzazz!
- Notfication Sound 

**Completion Deadline:** Oct. 4

# **Extras (optional)**
- [x] List of Achievments (in game)
- [ ] Infinity Game Mode 

# **Documentation**
- [Achievement Summary](../wiki/Achievement-Summary)

# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)

**Comment by SamBehm** [comment]
If you do get up to implementing an infinite mode, will the island continue to be able to expand, or reach a limit where the player has to work with what space they have?

**Comment by samsmarttt** [comment]
[16/10] I compared my designs and the achievement interface to make sure that it was suitable and cohesive with the pre-existing shop and inventory pages. Feedback was recieved from @mackenziekerr1 (team 6)

**Comment by samsmarttt** [comment]
[12/10] Spoke to @mackenziekerr1 (Team 6) about what i was trying to achieve this sprint, she provided feedback and validation for the achievements and the sprint 3 design. I proposed what i needed develop further, she provided feedback.
