### ISSUE TITLE
Add animations to structure designs

### ISSUE THREAD

**Issue by schmidem** [UQdeco2800/2022-studio-1#229]
# **Description**
We will build upon our finalised graphics by adding defensive animations to our designs. These include laser, trap, and aura animations which inflict damage onto enemies when they move within a predetermined radius of a given structure. Multiple design and user testing rounds will be conducted accordingly based on user feedback given.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Defence animations + user testing 
     - Undertake multiple rounds if applicable
- [ ] Offence animations + user testing 
     - Undertake multiple rounds if applicable
- [ ] General trap animations + user testing 
     - Undertake multiple rounds if applicable
- [ ] Claw trap animation + user testing
     - Undertake multiple rounds if applicable

**Completion Deadline:** Oct. 3

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Emma (@schmidem) (Emma Schmidley)
- Congxiao (@CongxiaoZhou) (Congxiao Zhou)
