### ISSUE TITLE
Team 8 NPC creation

### ISSUE THREAD

**Issue by KavyaMenda** [UQdeco2800/2022-studio-1#230]
# **Description**
An NPC (non-playable characters) is a bonus feature inclusive to Sprint 3 hoping to advance the gamified approach and plotline of Atlantis Sinks. Seen across many video games, it is "a character that is controlled by the computer rather than by a player". In the case of Atlantis Sinks, NPC's are not necessarily playing the game against the main character, but rather will be used to support the main character as they fight to protect the crystal. 
This process will ultimately entail extensive work on design, functionality alongside well-structured testing and validation.
 

## SubFeature/component (optional)
- Design the NPC 
Visual appearance of the non player character 

- Movement 
The  subfeature will craete the style of movement for the character 

# **Dependencies**
Depedency on Team 11 to make sure that both NPC charachters are unique 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 Flushing the details of the NPC (Aug. 20)
- [ ] Goal 2 Designing the NPC(Aug. 23)
- [ ] Goal 3 creation of entity class and other characters for the NPC(Aug. 26)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
-[ NPC Wiki ](https://github.com/UQdeco2800/2022-studio-1/wiki/NPC--by-Team8)
- ...

# **Members**
-Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
-Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
-Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
-Kavya Menda (@KavyaMenda) (Kavya)

**Comment by alexyun0429** [comment]
Hey Team 8, aren't you guys working with team 11? Because I see 2 feature tickets named the same, "NPC".

**Comment by KavyaMenda** [comment]
@alexyun0429 we have 2 tickets as 2 teams worked on enemy and they had 2 tickets ... similarly we are planning to make different  2 NPC
