### ISSUE TITLE
Implementing Camera Functionality for Player

### ISSUE THREAD

**Issue by SamBehm** [UQdeco2800/2022-studio-1#244]
# **Description**
**Task:** [Implementing Camera Functionality for Player](#244).
**Feature:** [Map/Environment Polishing](#238)

Currently the camera is withheld from a normal player, locked behind a debug mode. This task undertakes allowing the player to control the camera without being in debug mode, as well as altering the camera functionality. The new camera will function in the following way:
- Track the player as the character moves, keeping it in the centre of the screen;
- Allow the camera to zoom in and out using <kbd>Z</kbd> and <kbd>X</kbd> respectively;
- [The panning functionality will be guided by user-testing].

# **Milestones**
List of steps that need to be completed for this task.
- [x] Move the camera functionality out of debug (21/9)
- [x] Perform user-testing with the camera to guide camera functionality (22/9)
- [x] Implement functionality according to user-testing results (24/9)
- [x] User-testing to validate implementation (25/9)
- [x] Any changes needed due to user-feedback (26/9)
 
**Completion Deadline:** Sep. 26
 
# **Documentation**
- [Camera Operation](../wiki/Camera-Operation)
 
# **Member**
- Sam (@SamBehm) (sammm behm)
