### ISSUE TITLE
More enemy features on sprint 3

### ISSUE THREAD

**Issue by Louisouler** [UQdeco2800/2022-studio-1#245]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

New enemy feature
    - enemies remove when dead
    - range damage from buildings 
    - increasing diff every night

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Remove enemy if health point is 0 from the map (Sep. 15)
- [x] Update the heath bar component (Sep. 15)
- [x] Spawn multiple enemy according to the levels (Sep. 16)
- [x] Increase enemy status according to the levels (Sep. 17)
- [x] Update the calculation of the enemy health bar display (Sep. 18)
- [x] Range damage from buildings 
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yuhang (@1023790021) (Yuhang Lin)
