### ISSUE TITLE
Achievement Handler

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#249]
# **Description**
**Task:** [Achievement Handler](#249).
**Feature:** [Achievements](#224 )

This ticket is the creation of an achievement handler that provides service to the game in terms of which achievements have been achieved and which are outstanding. It is responsible for persisting the data across gameplay sessions! It will be used in different regions of the game to collect statistics to keep track of player progress towards the completion of achievements. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Handler (Sep. 21)
- [x] Create persistance (Save State) (Sep. 22)
- [x] Load State (Sep. 23)
- [x] Statistic Collection (Sep. 25)
- [x] WIKI Documentation (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Wiki documentation for achievement handler](../wiki/Achievement-Handler-Service)
- [JavaDoc](https://uqdeco2800.github.io/2022-studio-1/com/deco2800/game/services/AchievementHandler.html)
 
# **Member**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
