### ISSUE TITLE
Achievement Badge Design

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#250]
# **Description**
**Task:** [Task Name](#3).
**Feature:** (#224)

This task ticket regards the design process of the achievement badges. Various badge designs will be created for the achievement categories: Resources, Buildings, Kills, Upgrades, Game, Misc. To be used within the pop-up and the display page of achievements. Black and white colour scheme will be used to signify achievements which have not yet been completed. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draft Design (Sep. 22)
- [x] User Testing (Sep. 25)
- [x] Final Design (Sep. 26)
- [x] WIKI Documentation (Sep. 27)
- [x] Implementation of badges (Sep. 27)
 
**Completion Deadline:** Sep. 
 
# **Documentation**
- [Achievement design](../wiki/Achievement-Inspiration-&-Ideation)
- [User testing](../wiki/Achievement-User-Testing)
 
# **Member**
- Samantha Smart (@samsmarttt) (Samantha Smart)
