### ISSUE TITLE
Melee enemies continuous attack

### ISSUE THREAD

**Issue by MichelleAsWell** [UQdeco2800/2022-studio-1#255]
# **Make the melee enemies continuously attack**
**Feature:** [Save Game, Multiple Difficulties, and Enemy Attack Improvements](#221 )

Currently, melee enemies attack whatever they collide with once, on collision, then stop attacking. This is detrimental to the difficulty curve of the game, and means that once the enemy has collided with the crystal, there is no incentive to kill it. Changing this behaviour so that melee enemies attack continuously while colliding will improve the gameplay by raising the stakes. It is also more realistic that the enemies attack multiple times.

# **Dependencies**
- [ ] Melee enemies existing (#57 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Planning completed (Sep. 22)
- [ ] Implementation completed (Sep. 24)
- [ ] Tests completed (Sep. 25)
 
**Completion Deadline:** Sep. 25
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Michelle (@MichelleAsWell) (Michelle Sands)
