### ISSUE TITLE
Animate boss enemy character

### ISSUE THREAD

**Issue by Annabel-Kennedy** [UQdeco2800/2022-studio-1#260]
# **Description**
**Task:** [Animate boss enemy character]()
**Feature:** Save Game, Multiple Difficulties and Enemy Attack Improvements #221

The boss enemy character will be animated to improve users' visual experience and meet our emotional goals (i.e. users should fear the enemies, particularly the boss, when they appear). User testing will first be conducted to uncover whether the boss enemy is currently identifiable and portrays fear, danger etc. This step is important as currently user testing has only been conducted on the isolated boss enemy png before it was implemented in the game. Animations will be created based on user feedback and iterated further with more user input.

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Conduct user testing of boss enemy implemented in the game (Fri Sep 23.) 
- [x] Create sketches of boss enemy animation frames (Sun Sep 25.) 
- [x] Create high-fidelity pixel frames for animation (Wed Sep 28.)
- [x] User feedback on hi-fi animation and final changes (Fri Sep. 30)
- [x] Implement animations in game (Sun Oct. 2)
 
**Completion Deadline:** Sun Oct. 2

# **Extras**
 
# **Documentation**
- TODO [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Annabel (@Annabel-Kennedy) (Annabel Kennedy)
- Aleks (@a-siroki) (Aleks Siroki)

**Comment by Annabel-Kennedy** [comment]
Accidental duplicate
