### ISSUE TITLE
Achievement UX/UI 

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#267]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#224)

The creation of an achievement interface will allow for users to see the badges in which they have achieved, as well as the entire list of all the achievements able to be completed - specific for each category (Kills, Upgrade, Resources, Game, Misc, Buildings). Users will be able to access this page through both the main menu as well as during the game play session. The page will effectively categorise the badges through 2 column design. 

Statistic cards will showcase to users the progression of achievement completion through coloured numbered boxes. Remainding a light nuetral colour is not achieved as yet, once stage completed the colour will chnage green. Once all of the statistic components have been achieved, the user will have earnt the associated badge - represented with a green tick icon. However, if a badge has not yet been attained, it will be greyed out with a padlock. 

A progress bar may be implemented on each seperate achievement page, visually showcasing to users their progression. If progression is 100%, they have achieved all badges and can then work on fulfilling others. 

**Completion Deadline:** Oct. 18

# **Milestones Sprint 3**
List of steps that need to be completed for this task.
- [x] UI Draft Skeleton (Tabs, Scollable Content) (Sep. 26)
- [x] User Testing (Sep. 27)
- [x] Ability to switch between tab categories (Sep. 28)
- [x] Display Achievement Type Stats (Oct. 2)
- [x] Polishing and Achievement Finalisation (Oct. 2)
- [x] Wiki Documentation (Oct. 4)

**Completion Deadline:** Oct. 2

## **Stretch Goals**
- Progression bar on each category page
- Shaded badge card
- Achievement Summary Page 
- Achievement notification popup in game session

# **Documentation**
- [Achievement design](../wiki/Achievement-Inspiration-&-Ideation)
- [User testing](../wiki/Achievement-User-Testing)
 
# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
