### ISSUE TITLE
Spawn buildings in map on key press

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#27]
# **Description**
**Task:** [Spawn buildings in map](#3).
**Feature:** [#10 ](#2)

Implement functionality to spawn buildings into the map upon key press. 
 
## **Example (optional)**
- **Interface Functionality**: Upon pressing specific buttons, buildings are created and spawned into the map. 

# **Dependencies**
- [x] #25 
- [x] #51

# **Milestones**
List of steps that need to be completed for this task.

- [x] Finish building sprites (Aug. 24)
- [x] Implement keybinds (Aug. 26)
- [x] Update Wiki documentation
 
**Completion Deadline:** Aug. 26

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Harland (@harland-jensen) (Harry Jensen)
