### ISSUE TITLE
Inventory page layout implemented

### ISSUE THREAD

**Issue by Tianyuanhaimo** [UQdeco2800/2022-studio-1#270]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Inventory page layout implemented](#205)

In Sprint3, the basic layout of the user Inventory is implemented. Users can view purchased equipment, buildings and other items.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] fix shop layout (Aug. 19)
- [ ] Create inventory Screen (Aug. 20)
- [ ] add inventory parts (Aug. 23)
- [ ] Try changing Inventory to a popover(Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
