### ISSUE TITLE
Shop feature finalization

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2022-studio-1#272]
# **Description**
**Task:** Shop feature finalization 
**Feature:** [Inventory](https://github.com/UQdeco2800/2022-studio-1/issues/205)

Adding the last shop category, building. As well as changing some combat stat component storing.
 
# **Milestones**
- [x] Change combat stat code
- [x] add building json files to game
- [x] adding buildings into shop and relevant backend data storage
**Completion Deadline:** Aug. 23

# **Member**
- e.g. Cheng-Yu Lin (@Lumin-cider ) (Lumin-cider)
