### ISSUE TITLE
Create NPC and spawn NPC into game based on number of buildings on map

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#274]
# **Description**
**Task:** [Create NPC and spawn NPC into game base on number of buildings on map](#3).
**Feature:** [NPC Creation](#230 )

Create/modify function to create NPCs and implement function to spawn NPC into the game. Number of NPCs spawned is relative to number of buildings on the map to ensure the map is not too crowded. The type of NPCs spawned will be randomized to add a sense of uncertainty/surprise for players. NPCs will spawn during the day and disappear at night to avoid attack from the enemies. 
 

# **Dependencies**
- [ ] Dependency 1 
Dependent on team 11 to add animation/detail when NPC entities are disposed at night (Eg. NPC running to the crystal to hide)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 19) Develop/Modify function to create NPC
- [x] Step 2 (Sep. 20) Implement function to spawn NPC based on number of buildings on map and part of day 
- [x] Step 3 (Sep. 21) Enable randomization of NPC texture/type
- [x] Step 4 (Sep. 22) Create NPC service to handle events regarding NPCs
- [x] Step 5 (Sep. 25) Avoid NPCs going out of bounds (on water)

 
**Completion Deadline:** Sep. 25

 
# **Documentation**
-[[ NPC Wiki ](https://github.com/UQdeco2800/2022-studio-1/wiki/NPC--by-Team8)](https://github.com/UQdeco2800/2022-studio-1/wiki/Non-Playable-Characters-(NPCs))

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
