### ISSUE TITLE
Enable players to have conversation with NPCs by clicking on them

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#275]
# **Description**
**Task:** [Enable players to have conversation with NPCs by clicking on them](#3).
**Feature:** [NPC Creation](#230 )

Players will be able to have conversation with NPCs by clicking on them. By having conversation with certain NPCs, there is a chance that the player will receive something in return. 
 

# **Dependencies**
- [ ] Dependency 1 
Dependent design team/team 11 to create NPC talking animation
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 23) Develop function to determine if an NPC is clicked by player
- [x] Step 2 (Sep. 24) Create class and implement functionality for UI pop up of conversation 
- [x] Step 3 (Sep. 25) Implement variety/randomization of dialogues
- [x] Step 4 (Sep. 26) Implement functionality for NPCs to give something to the player 

 
**Completion Deadline:** Sep. 30

 
# **Documentation**
-[[ NPC Wiki ](https://github.com/UQdeco2800/2022-studio-1/wiki/NPC--by-Team8)](https://github.com/UQdeco2800/2022-studio-1/wiki/Non-Playable-Characters-(NPCs))

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
