### ISSUE TITLE
Audio & Music

### ISSUE THREAD

**Issue by mattbezett** [UQdeco2800/2022-studio-1#28]
# **Description**
Team 11 will work on creating and implementing audio and music into the game. We will collaborate with other teams to create audio that matches the aesthetic and theme of the rest of the game. Sound effect and music cues will then be implemented throughout the code as necessary. Audio is very important for all games to build immersion, convey the theme of the game and connect players to what they're seeing. In the final product, audio will be prevalent troughout the game; different music will play depending on what's happening, and sound effects will play ambiently, for player actions and for enemies.

# **Dependencies**
- Enemy sounds will depend on their appearance and behaviour
- Music will depend on day / night cycle
- Players will require a menu to toggle music & sound on / off

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Aug. 20)
- Create a plan for most important sound effects, e,.g. must have, could have
- Create an `AudioManager` class
- Begun creating sound effects and music
- [x] Goal 2 (Aug. 23)
- Basic "Must Have" audio events implemented
- [x] Goal 3 (Aug. 26)
- Music based on day/night cycle implemented
- [ ] Goal 4 (Aug. 28)
- Finalised implementation, integrated with other classes
- Testing complete

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Implement audio for hovering over keys.
- [ ] Implement audio for clicking keys.
- [ ] Implement pause/play/mute function in UI.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Matthew Bezett (mattbezett) (Matthew Bezett)
- Reuben Joseph (ReubenJOJO) (Reuben Joseph)
- Wanqi Ma (lalala66888) (Wanqi Ma)
- Yincheng Wu (tinymuscle) (Yincheng Wu)
