### ISSUE TITLE
Shop Enhancements

### ISSUE THREAD

**Issue by hthaesler** [UQdeco2800/2022-studio-1#283]
# **Description**

While the shop functionality has been completed the design aspect of the feature needs to be enhanced to effortless suit the design of the overall game, and allow the user to subconsciously understand that the shop is in fact a shop. 

This will allow for the design of the game to not seem disjointed and to subconsciously play on the user's understanding of shops and how they function. To make them think "Oh I can buy objects here", and to enhance the experience of the 'shop'. 
 
# **Milestones**
List of steps that need to be completed for this task.
Step 1 (Sept. 21)
- [ ] Plan changes to enhance the shop feature
- [ ] Pros and cons of making these changes 
- [ ] Feedback from previous sprints

Step 2 (Sept. 24)
- [ ] Wireframes designed for changes to be implemented 
- [ ] Iterations completed 
- [ ] User testing on the emotional response to designs and which seem more comfortable for a shop layout

Step 3 (Sept. 29)
- [ ] Designs finished and shared with the group for feedback 
- [ ] Confirm designs 

Step 4 (Oct. 1)
- [ ] Implementation of the new designs 

Setp 5 (Oct. 3)
- [ ] Testing and validation of changes
 
**Completion Deadline:** Oct 4
 
# **Member**
- Hannah Thaesler (@hthaesler) (Hannah Thaesler)
