### ISSUE TITLE
Design Structure Types

### ISSUE THREAD

**Issue by jonooallen** [UQdeco2800/2022-studio-1#29]
# **Description**
**Task:** [Design Structure Types](#xx).
**Feature:** [Building Infrastructure / Towers](#10)

The team will design at least one of all buildable structures in the game. These structures will include objects such as towers, bridges, walls, etc. Designing these structures include understanding specific use cases, designing the structure, and creating aesthetic and variable assets to accompany the object.

# **Dependencies**
- [x] #50 
- [x] #51 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] List of all intended buildable structures (Aug. 18)
- [x] Designs of game infrastructure (Aug. 20)
- [x] Creation of infrastructure assets and textures (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Emma (@schmidem) (Emma Schmidley)
- Harland (@harland-jensen) (Harry Jensen)

**Comment by schmidem** [comment]
**01/09/2022**
Object design guide decisions were finalised for Sprint 2 with @samsmarttt
