### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by cholnhial** [UQdeco2800/2022-studio-1#3]
# **Description**

Addition of enemies into game including ranged and melee varieties. The enemies spawn from the surrounding water at night and attempt to reach the crystal to inflict damage on it. Included to add adversity to the game adds the means by which the player could lose.

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.
### Melee Attack enemies

Melee enemies are only able to attack objects that are directly in front of them and so will attempt to path straight to the player crystal along the shortest path. If the player is between the enemy and the crystal, the enemy will attack the player instead.

### Ranged Attack enemies

Range enemies use projectiles to attack targets in front of them and can follow them. They will move towards the crystal. 

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.

# **Dependencies**

- Enemies spawning at night relies on night cycle being implemented.
- Enemies moving towards the player crystal depends on the existance of a crystal.
- Enemies attacking objects depends on implementation of buildings and collidable objects for the enemies to attack.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Create sprite sheet (Aug. 20)
- [ ] Enemies spawn at night (Aug. 23)
- [ ] Enemies move towards crystal (Aug. 26)
- [ ] Enemies attack objects in front of them (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
