### ISSUE TITLE
Inventory display and Item usage

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2022-studio-1#300]
# **Description**
**Task:** inventory display and item usage
**Feature:** [Inventory](https://github.com/UQdeco2800/2022-studio-1/issues/205)

import all inventory items to visually display inventory in maingame and implement item effects to game

e.g.
- [x] implement health potion function to fully restore player health
- [x] implement clock function to give player invincibility for 5s
- [x] implement bed function to auto regen player health for 15s
 
# **Milestones**
- [x] Visually display inventory (Oct. 2)
- [x] Implement all item function (Oct. 2)
 
**Completion Deadline:** Oct. 3

# **Member**
- e.g. Cheng-Yu Lin (@Lumin-cider) (Lumin cider)
