### ISSUE TITLE
Ranged enemy Animation 

### ISSUE THREAD

**Issue by hblakeway** [UQdeco2800/2022-studio-1#303]
# **Description**
**Task:** Ranged enemy animation integration 
**Feature:**Eel animation

Implement ranged enemy animation

# **Dependencies**
- [x] Eel character atlas and sprite sheet
- [x] Starfish character atlas and sprite sheet 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find relevant animation classes(Sep. 22)
- [x] Implement code for animation (Sep. 24)
- [x] Test animation code (Sep. 26 )
 
**Completion Deadline:** 26th September 

# **Documentation**
- [Main description of technical animation](https://github.com/UQdeco2800/2022-studio-1/wiki/Eel-Animation)
 
# **Member**
- @hblakeway
