### ISSUE TITLE
Eel Design improvements 

### ISSUE THREAD

**Issue by hblakeway** [UQdeco2800/2022-studio-1#304]
# **Description**
**Task:** Eel Design 
**Feature:** Improving eel design in game environment 

Test and evaluate necessary design changes for eel - if any. 
 
# **Dependencies**
None 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Studio Test eel (Sept. 26)
- [x] User Test eel (Sept. 26)
- [x] Begin research and initial sketches around water based eel designs (Oct. 2)
 
**Completion Deadline:** (Oct. 2)

e.g.
# **Documentation**
- [Main description of water based eel](https://github.com/UQdeco2800/2022-studio-1/wiki/Changes-to-Eel-Design-Sprint-3)

 
# **Member**
- @hblakeway
