### ISSUE TITLE
 Initialize the game map

### ISSUE THREAD

**Issue by taylaward** [UQdeco2800/2022-studio-1#31]
# **Description**
**Task:** [Initialize the game map]
**Feature:** [Map General and Water Metrics](#30) [

Implement game map as an Array. The game map will have a fake height feature. 

Create how the map will be generated at the ground level. Create functionality of adding level (height) to the map.

# **Dependencies**
- [x] Tile textures need to be made (#xx)
 
# **Milestones**
- [x] Create Array(Aug. 19)
- [x] Create Map Generation (Aug. 20)
- [x] Create different tile generations (Aug. 23)
- [x] Set World Border (Aug. 25)
- [x] Implement Icon Textures(Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
Needs to be creates
 
# **Member**
