### ISSUE TITLE
Inventory functionality

### ISSUE THREAD

**Issue by venndiagram5** [UQdeco2800/2022-studio-1#313]
# **Description**
**Task:** [Inventory](#205).

Implement various functionality required for inventory.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] update shop background and buy button (Oct 2)
- [x] implement arm and disarm in inventory (Oct 3)
- [x] implement building placement (Oct 3)
- [x] implement  (Oct 4)
 
**Completion Deadline:** Oct 4
 
# **Member**
- Satya Bhasale (@venndiagram5 ) (Satya Bhasale)
