### ISSUE TITLE
SaveGame

### ISSUE THREAD

**Issue by MichelleAsWell** [UQdeco2800/2022-studio-1#316]
# **Description**
This should be roughly a one paragraph description of the features / ideas on which your team plans to work. It should very briefly touch on why you think it should be in the game (e.g. "Adds an extra layer of depth to game play"). It should also describe how it will appear or be used in the final product (e.g. "On starting a level, the game will generate a random, procedurally-generated map").

## SubFeature/component (optional)
- [ ] Save enemies
- [ ] Save daynightcycle
- [ ] Fix buildings save
- [ ] Fix EnvironmentalObjects save
- [ ] Fix the shop window thing (talk to team 6 - Lumin)
- [ ] Tests written
- [ ] Code cleanup & bug fixes
- [ ] Misc tests for code coverage

## **Examples (optional)**

# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Aug. 20)
- [ ] Goal 2 (Aug. 23)
- [ ] Goal 3 (Aug. 26)
- [ ] Goal 4 (Aug. 28)

**Completion Deadline:** Oct. 18

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Michelle (@MichelleAsWell) (Michelle Sands)
