### ISSUE TITLE
Juicy UI

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#320]
# **Description**
Since the guidebook, home screen and settings page, and general UI are functional in the game, our team will now work on making the game more interactive and improving the presentation of all UI features.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
Goal: 9th October:
- [ ] Load Page 
- [ ] UI Buttons (Hover) 
Goal: 12th October
- [ ] Fixing UI Building 
- [ ] Animation on Guidebook
Goal: 16th October
- [ ] Linking Guidebook Table on Content. 
- [ ] Home Page/ Settings Animation 
- [ ] User Testing  

**Completion Deadline:** October 18th
# **Extras (optional)**
- [ ] Player Health Vignette

# **Documentation**
- [Jucieness Explanation]()
- [Animation]()
- [Implementation]()

# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)
Aviral Sharma (@4vir4l)
