### ISSUE TITLE
Overall Map Obstacles Design and Implementation

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#321]
# **Description**
Throughout sprint 4, the team will conduct multiple user testing, redesign, modify, create and implement obstacles (infrastructure). These include all the turrets, walls and natural components. Also, the team will collaborate much with team 13 to solve the main concern which is the infrastructure. Moreover, there will be add-ons to natural components as well. 

## SubFeature/component (optional)
- User testing
The team would have to conduct user testing on the previous design of the infrastructure

- Modification of existing design works
Based on the feedback there will be modifications or new designs to the infrastructure
Modification of the existing map components (ex. tiles) as well

- Create necessary new infrastructure
If the result of user testing shows the necessity of redesign needs, the team will conduct design process.

# **Dependencies**
- Environmental Objects Design and Functionality (#241)
- Map/Environment Polishing (#238)
- Add animations to structure designs (#229)
- Finalise building designs (#209)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Make user testing plan and agenda for previous work (Oct. 08)
- [ ] Conduct User testing on previous work (Oct. 09)
- [ ] Group discussion on the result of user testing (Oct. 09)
- [ ] Research to reference for future design work (Oct. 10)
- [ ] Start design with the result of the group discussion (Oct. 13)
- [ ] Implement newly designed work (Oct. 14)
- [ ] User testing of new implementation (Oct. 16)
- [ ] Modification and implementation (Oct. 17)
- [ ] Wiki writing (Oct. 17)

**Completion Deadline:** Oct. 17

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
- Emily (GitHub Username) (Slack Handle)
- Pragun Ramesha (Xodacan)

**Comment by mackenziekerr1** [comment]
Hey Team 12! Just confirming that we have received your updated sprites & these have been added into the shop. Thanks! :)
