### ISSUE TITLE
Player/Enemy Positional UGS Updates

### ISSUE THREAD

**Issue by luke4641942** [UQdeco2800/2022-studio-1#325]
# **Description**
**Task:** [Player/Enemy Positional UGS Updates](#325)
**Feature:** [UGS Complete Integration](#319)

This task will be focused on the completion of the UGS integration; primarily moving the player and enemies within the UGS so the Range Service's Functions will function properly. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Research all relevant classes and functions around UGS (Oct. 6)
- [x] Impliment relevant methods and functions (Oct. 9)
- [x] Debug/Test (Oct. 10)
 
**Completion Deadline:** Oct. 10

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Luke (@luke4641942) (Luke Graham)
