### ISSUE TITLE
Fixing Environmental and Structure Save Game

### ISSUE THREAD

**Issue by Logan-De-Groot** [UQdeco2800/2022-studio-1#327]
# **Description**
**Task:** Fixing Environmental and Structure Save Game
**Feature:** [SaveGame](#316) 

Since the conclusion of Sprint 3 save game has had some functionality broken regarding the Environmental and Structural placement most likely due to the implementation of the universal grid system #208. This task aims to fix and reimplement functionality as needed to Save and Load Environmental and Structural Entities once again. This will hopefully be done via a similar method to previousally which was JSON serialisation of key important features. Ideally only minor fixes will be made but it is possible that a full rework is required depending on the extent of changes.

# **Dependencies**
- [Save Game](https://github.com/UQdeco2800/2022-studio-1/issues/221)]
- [Enviromental Objects](#6)
- [Structures](#10)
-[UGS](#208)

# **Milestones**
List of steps that need to be completed for this task.
- [x]  (Oct. 7) Investigation of Refactoring and Possible Solutions

After investigation it was determined that UGS while breaking the Save Game functionality requires some rework and loading and saving of additional information such as position in tiles. On top of this it was decieded that additional steps need to be taken and a transisition to stack tracing for invocation is needed.
- [x] (Oct 10) Fix Enviromental
- [x] (Oct 11) Fix Structurees
- [x] (Oct 14) Convert to Stack Tracing and clean up
- [x] (Oct 15) rewrite and finish unit tests as needed
 
**Completion Deadline:** Oct 15 Deadline
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Logan De Groot (@Logan-De-Groot)
