### ISSUE TITLE
Animation on Guidebook

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#329]

**Comment by tgarnsworthy** [comment]
### Description

To boost the juiciness of the guidebook, the plan is to integrate animations of the currently stationary graphics. Animation has the capacity to capitivate the user through engaging means to make the user feel enticed, develop a sense of familarity in the game and express the guidebook message quicker. We believe making the guidebook more interactive in this way will improve the usbaility and juiciness!

### Milestones/Deliverables 
Date - 12/10/22
- [ ] Sketch out animations for each page (low-fidelity prototypes)
- [ ] Try and cut down on words in current guidebook state
Date - 14/10/22
- [ ] Compile images and graphics used in the animations
- [ ] Create a file which stores the animations
Date - 16/10/22
- [ ] Implement code to make the animations work 
- [ ] Update the JSON file for formatting
