### ISSUE TITLE
Design pixel art for single block of map

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#33]
# **Description**
**Task:** [Design pixel art for a single block of map](#30).
**Feature:** [Map - block pixel design](#2)

The team will design a block for a map in pixel art.
The map is going to be in 2D (looks like 3D), therefore, each block has to be designed in pieces of squares or triangles. 
It is because the code will generate the map like a chessboard. Once, the pieces are designed, then we will combine them to look like one block. 
Before we get into further details of the block, will finalise the outline of each block according to the map tile.

# **Dependencies**
There are no dependencies for a block design.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise how to cut and combine the square to make a block shape on the map. (Aug. 19)
- [x] Design each decided shape into pixel art style. (Aug. 21)
- [x] Get feedback and implement (ex. colour, style, etc) (Aug. 22)
- [x] Finalise the default block style (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Emily-Kate Williams (@ek-williams) (Emily-Kate Williams)
- Jae Won Yun (@alexyun0429) (JaeWon Yun)
- Pragun Ramesha (@Xodacan) (Pragun Ramesha)
- Sam Behm (@SamBehm) (Sam Behm)
- Tayla Ward (@taylaward) (Tayla Ward)
