### ISSUE TITLE
UI Buttons (Hover)

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#332]

**Comment by Olivialeighton** [comment]
# **Description**
Ensure that all buttons have a hover state and that it is implemented to increase juiciness of the game. 

# **Milestones**
- [x] Find all buttons that do not have a hover state or do not match (5th of Sept)
- [x] Make hover states for the buttons if not already make (8th of Sept)
- [x] Implement these hover states(9th of Sept) 
 
**Completion Deadline:** October 12th

# **Documentation**
 
# **Member**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)
