### ISSUE TITLE
Create user testing plan and agenda for previous work

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#335]
# **Description**
**Task:** [User testing on previous sprint works](#3).
**Feature:** [Overall Map Obstacles Design and Implementation](#321)

This will only create the questions, agenda and planning on how user testing on the previous sprint design is going to happen.

# **Dependencies**
- (#241 )
- (#209 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide what to ask the user (Oct. 7)
- [x] Make the questions (Oct. 8)
- [x] Group discussion (Oct. 8)
 
**Completion Deadline:** Oct. 8

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
- Emily-Kate Williams (@ek-williams ) (Emily Williams)
- Pragun Ramesha (Xodacan)
- Xi Wang (XiWangBeryl)
- Suki Zhang (@sukizzz) (Suki Zhang)
