### ISSUE TITLE
Conduct user testing on previous sprint works

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#336]
# **Description**
**Task:** [Conduct user testing](#3).
**Feature:** [Overall Map Obstables Design and Implementation](#321 )

 The team will conduct user testing sessions to gather feedback on previous infrastructures' designs. According to the feedback, the team would decide to re-design it or modify it to implement it on the map.
 
# **Dependencies**

- (#335)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Distribute user testing document (Oct. 8)
- [x] Conduct user testing (Oct. 9)
- [x] Gather feedback (Oct. 9)
- [x] Group discussion to decide on a design (Oct. 9)
 
**Completion Deadline:** Oct. 9

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
- Emily-Kate Williams (@ek-williams ) (Emily Williams)
- Pragun Ramesha (Xodacan)
- Xi Wang (XiWangBeryl)
- Suki Zhang (@sukizzz) (Suki Zhang)
