### ISSUE TITLE
Design - the result of the group discussion (Oct. 13)

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#338]
# **Description**
**Task:** [Design - the result of the group discussion](#3).
**Feature:** [Overall Map Obstables Design and Implementation](#321 )

The team starts the design work according to task distribution. There will be three turrets and each turret have three levels, three different traps and several walls.
Distribution:
3 people will get 1 turret each.
1 person will get 3 traps.
1 person will get several wall designs.
 
# **Dependencies**

- (#336)
- (#337)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Start design (Oct. 10)
- [x] Send it to group chat to discuss on progress (Oct. 12)
- [x] Finalise it (Oct. 13)

**Completion Deadline:** Oct. 13

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- JaeWon Yun (@alexyun0429 ) (JaeWon Yun)
- Emily-Kate Williams (@ek-williams ) (Emily Williams)
- Pragun Ramesha (Xodacan)
- Xi Wang (XiWangBeryl)
- Suki Zhang (@sukizzz) (Suki Zhang)
