### ISSUE TITLE
Implement water rising and how it affects height levels

### ISSUE THREAD

**Issue by taylaward** [UQdeco2800/2022-studio-1#34]
# **Description**
**Task:** [Implement water rising and how it affects height levels](#3).
**Feature:** [Map Generation and Water Metrics](#30 )
Rules, water can only go up or down one level, can’t skip a level etc.

Implement water rising and falling functions. Also implement the automatic water rising per (metric to be decided). Implement water rising rules (Water rising cannot 'skip' a level height).

# **Dependencies**
- [ ] Initialise Map (#31 )
- [ ] Tile Textures (#33 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement water rising and falling functions (Aug. 19)
- [ ] Implement automatic water rising per metric (Aug. 20)
- [ ] Implement Rising rules (Aug. 23)
- [ ] Add Textures to the water(Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
To be implemented
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
