### ISSUE TITLE
Day & Night Cycle Improvements

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#344]
# **Description**
This ticket regards the imporvements which will be made to the day and night cycle features.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Adjustment of shader values (Oct. 12)
- [x] Removal of shader affects key (Oct. 12)
- [x] Fade transition between cycles (Oct. 13)
- [ ] Clock save state (Oct. 17)

**Completion Deadline:** Oct. 18

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
