### ISSUE TITLE
Addition of remaining achievements

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#345]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task tickets regards the addition of the remaining achievements, both stat and non stat. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Creat respective events for remaining achievements (Oct. )
- [ ] Play tests (Oct. )
- [ ] Create new classes for custom achievement data - if necessary (Oct. )
 
**Completion Deadline:** Oct. 

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Members**
- Chol Nhial Chol (@cholnhial) (Chol Nhial)
- Pranav (@Pranav2087)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
