### ISSUE TITLE
Improving UI elements and adding animations

### ISSUE THREAD

**Issue by schmidem** [UQdeco2800/2022-studio-1#346]
# **Description**
We are focusing on enhancing the pre existing UI components in the game to better suit the consistency and design of the overall game. We will be looking at different UI elements, including animation in the game, and conduct extensive user testing of the game (as opposed to prior user testing that has focused on isolated single features). This new user testing will help us identify different design elements which require improvement, such as incorrect size, misaligned proportions, typography and various shape or color inconsistencies. Furthermore, we will be introducing new design principles and updating the design style guide accordingly. These guidelines will be communicated to other teams’ designers through the design committee.

**Goal:** To ensure that the overall design direction is more consistent, cohesive and adheres to the updated design guidelines, which will be based on user testing and the guidelines created in sprint 1.

## SubFeature/component
- Improving Style Guide from updated user testing.
- Creating design consistency of on-map UI elements

This includes design of elements like buildings, main character, trees, walls to adhere to an updated style guide set by our team through user testing and simultaneously redesigning these elements to make sure they match the new guideline to improve the feel of all the playable elements in the game to appear more consistent.

- Creating design consistency of off-map UI elements

This includes design of elements like buttons, icons, typeface, cutscenes, shop screen, titles, headings, typefaces and the other non playable aspects of the game to adhere to an updated style guide set by our team through user testing and simultaneously redesigning these elements to make sure they match the new guideline to improve the feel of all the non-playable UI elements in the game to appear more consistent.

- Enemy Animation

So far through the sprints, animations were enforced as a part of the game design and there are some areas where the animations are inconsistent or do not exist at all, our team would be designing animations for the elements that are not currently animated in the game. By a quick look at the game, the enemy crab is missing animation which our team would work towards implementing. Furthermore, upon the results of the prior user testing, any UI element that has the need to be animated to ensure the overall consistency would also be implemented.

- Design Committee (Extra) 

The main goal of the Design Committee is to ensure consistency across all game components. The problem stems from the necessity to establish clear guidelines so that other designers are aware what design direction they need to choose.

# **Dependencies**
[UI Style Guide Design Guidelines](https://github.com/UQdeco2800/2022-studio-1/wiki/Design-Guidelines)
[Building UI Overview](https://github.com/UQdeco2800/2022-studio-1/wiki/Building-UI-Overview)
[Target Audience Analysis](https://github.com/UQdeco2800/2022-studio-1/wiki/target-audience-analysis)
[Primary User Group](https://github.com/UQdeco2800/2022-studio-1/wiki/Primary-User-Group)
[Design Committee Research](https://github.com/UQdeco2800/2022-studio-1/issues/356)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Complete extensive user testing of the game (Oct. 11)
- [x] Analyse user testing results and create guidelines to be shared with and approved by design committee (Oct. 12)
- [x] Identify designs and animations for our team to edit to improve consistency (Oct. 12)
- [x] Implement all improved designs and animations ( Oct. 18)

**Completion Deadline:** Oct. 18

# **Extras (optional)**
- [x] Identify patterns and frequent design flaws to help other teams in the future maintain consistency and cohesion

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Suhas Udupa (@suhasudupaa) (Suhas Udupa)
- Emma Schmidley (@schmidem) (Emma Schmidley)
- Rohan Teotia (@RohanTeo) (Rohan Teotia)
- Aleks (@a-siroki) (Aleks Siroki)
- Annabel (@Annabel-Kennedy, Annabel Kennedy)

**Comment by schmidem** [comment]
6/10/2022- Team meeting with @ChevScore relating to the Design Committee. From this discussion it was decided that our team will become the Design Committee. The Design Committee will be a sub team that focuses on design cohesion specifically between the different game components. This decision was also based on previous discussions @ChevScore had with other studio teams who agreed on the idea of having a sub team with this focus.
