### ISSUE TITLE
Team 8 - Sprint 4 Crystal Feature Ticket

### ISSUE THREAD

**Issue by sheehamishra** [UQdeco2800/2022-studio-1#347]
# **Description**
Continuing work with the Crystal, this feature will see further work to achievements of the crystal particularly. From Sprint 2, the crystals functionality was its ability to upgrade on click and for the health to restore. In our attempt to finalise the crystal feature, Sprint 4 will see a general ‘clean up’ performed. Specifically in terms of popup and integration, crystal death animation, potential code smells. 

## SubFeature/component (optional)
Crystal upgrade popup and integration - To enhance general user experience, ensuring a message is delivered to the user upon crystal upgrade to signify a somewhat achievement. 
Crystal death animation - this is in reference to the crystal health bar, specifically portraying when it reaches a health score of 0. 

# **Dependencies**

- Dependency on the UI team in designing popup background for crystal upgrade
- Design touch-up and collaboration with newly devised Design Committee

# **Milestones**
Programming Goals
- [ ] Goal 1: Crystal upgrade popup and integration (Oct. 11)
- [ ] Goal 2: Crystal death animation (Oct. 13)
- [ ] Goal 3: Test Write-Up (Oct. 15)
- [ ] Goal 4: Crystal code smells and warnings Sonarcloud code coverage (Oct. 17)

Design Goals
- [ ] Goal 1: Crystal death animation refinement
- [ ] Goal 2: Popup background design collaboration with UI team and Design Committee

**Completion Deadline:** Oct. 18

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
- Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
- Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
- Kavya Menda (@KavyaMenda) (Kavya)
