### ISSUE TITLE
Bug fixes & Improving SonarCloud score

### ISSUE THREAD

**Issue by JumpOffACliffy** [UQdeco2800/2022-studio-1#354]
# **Description**
As part of the polishing process for sprint 4, we will be doing a general cleanup of the code. This includes implementing functionality not yet completed as well as fixing bugs and improving the overall quality of the code. 

## Tasks
- [ ] 0 bugs under the SonarCloud Reliability section
- [ ] 0 security hotspots under the SonarCloud Security Review section
- [ ] Reduce code duplication to 3%
- [ ] Increase test code coverage

**Completion deadline:** October 15

## **Members**
- Cliff Worsfold (@JumpOffACliffy)
