### ISSUE TITLE
Crab enemy animations

### ISSUE THREAD

**Issue by Annabel-Kennedy** [UQdeco2800/2022-studio-1#358]
# **Description**
**Task:** [Crab enemy animations](#3)
**Feature:** [Improving UI elements and adding animations](#346 )

As the crab enemy is the only enemy without animation sprites, animation sprites will be created and implemented for this enemy. The aim of this task is to improve user engagement with the implementation of new animations and to improve design consistency by ensuring all enemies are animated when moving. User testing conducted by other members of team 15 will help inform the style of these animations.

# **Dependencies**
The style in which these animations will be created will be dependent on team 15's user testing: [Improving UI elements and adding animations](#346 )
 
# **Milestones**
- [ ] Create sketches of animation sprites (Oct. 12)
- [ ] Conduct user testing on sketches and implement changes (Oct. 13)
- [ ] Create hi-fi pixelated sprites (Oct. 16)
- [ ] Implement animations (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Annabel (@Annabel-Kennedy, Annabel Kennedy)

**Comment by Annabel-Kennedy** [comment]
Met with @MichelleAsWell - who implemented the final boss animations last sprint - to discuss how previous animations had been implemented in the game.

**Comment by Annabel-Kennedy** [comment]
![image](https://user-images.githubusercontent.com/83194467/196096821-d4eee45d-ea20-4fa0-a123-7f2477a37f9e.png)

Consulted with the "bug-fixing-legends" channel on Discord as my animation implementation was failing newly implemented tests. Was told to comment the tests out as they would be updated later on.
