### ISSUE TITLE
Range Buildings [Final Implementation]

### ISSUE THREAD

**Issue by SamBehm** [UQdeco2800/2022-studio-1#360]
# **Description**
**Task:** [Range Buildings Final Implementation(#3).
**Feature:** [Polishing Structures](#317)

Defensive ranged buildings has been planned to be implemented since Sprint 1, with some of the architecture required for the implementation having been completed over previous sprints. Defensive ranged buildings are necessary to the game as it allows the player to defend the island against enemies without being present. This is important as with the later island sizes, it's hard to defend all points of attack over a large distance.

# **Milestones**
- [ ] Create Turret Structure (Oct. 12)
- [ ] Implement Turret Sprites  (Oct. 12)
- [ ] Write JUnit Tests for Turret Implementation (Oct. 13)
- [ ] Test Current Implementation of Projectiles (Oct. 13)
- [ ] Implement Ranged Attack for Turrets  (Oct. 14)
- [ ] Perform User-Testing for implementation of Turrets (Oct. 15)
- [ ] Perform Play-Testing for implementation of Turrets (Oct. 15)
- [ ] Implement any changes needed (Oct. 16)
- [ ] Write Documentation for Turret Structure (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sam Behm (@SamBehm ) (sammmbehm)
