### ISSUE TITLE
Team 1 User Testing 

### ISSUE THREAD

**Issue by hblakeway** [UQdeco2800/2022-studio-1#365]
# **Description**
**Task:** User testing
**Feature:** Ranged enemy user testing 

Testing conducted to evaluate the designs, movement and tasks done by ranged enemies
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Send out user testing (Oct. 7)
- [ ] Analyse user testing (Oct. 14)
- [ ] Apply User testing results(Oct. 16)
 
**Completion Deadline:** Oct. 16

# **Documentation**
- [Main description of feature](../wiki/Feature)

 
# **Member**
- Team 1
