### ISSUE TITLE
 Design pixel art for blocks (detailed style)

### ISSUE THREAD

**Issue by alexyun0429** [UQdeco2800/2022-studio-1#37]
# **Description**
**Task:** [ Design pixel art for blocks (detailed style)](#3).
**Feature:** [Map / Single map block](#2)

This is where the team is going to design specific blocks in detail according to situations and types.
Also, it matters by day and night time of the game.

# **Dependencies**
- [ ] Design pixel art for single block of map (#33 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design of each type of block (Aug. 19)
- [ ] Differ the colour base on day and night (Aug. 20)
- [ ] Differ the colour intensity by usage (Aug. 23)
 
**Completion Deadline:** Aug. 23
ation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- JaeWon Yun (@alexyun0429)(JaeWon Yun)
