### ISSUE TITLE
shop and inventory component updated

### ISSUE THREAD

**Issue by Tianyuanhaimo** [UQdeco2800/2022-studio-1#386]
# **Description**
update shop and inventory component
**Task:** shop and inventory
**Feature:** [Shop & Inventory Refinements](#315 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ]  update file path for arming the main character with different combinations of weapons
- [ ] implementation of buttons changing colour on click (Aug. 20)
- [ ] update pricing of items (Aug. 23)
- [ ] change sprites for items in the shop (Aug. 23)
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
