### ISSUE TITLE
Design Style and Cohesion Guidelines

### ISSUE THREAD

**Issue by a-siroki** [UQdeco2800/2022-studio-1#392]
# **Description**
From solving current design problems to ideating on possible new features the purpose of this ticket is to develop a resource or a guide that would be used by all designers despite their focus area. The concept is evolved around the need to introduce guidelines specific enough to be acted as a checklist/criteria for designers when confirming their design's consistency. This ensures that every designer reduces time needed to get feedback. Furthermore, from design cohesion perspective these guidelines will help with the verification on whether the design fits into the game overall style direction. 
 
## **Example of usage**
- **Design Style**: guidelines that can be used by other designers to "_self verify_" the design direction for the Atlantis Sinks game.
- **Design cohesion**:  explanation on how to verify whether the design fits into the game based on the overall theme of the game

# **Dependencies**
Following tickets will be used as references to support the documentation and the creation of the final guide.

[UI Style Guide Design Guidelines](https://github.com/UQdeco2800/2022-studio-1/wiki/Design-Guidelines)
[Building UI Overview](https://github.com/UQdeco2800/2022-studio-1/wiki/Building-UI-Overview)
[Target Audience Analysis](https://github.com/UQdeco2800/2022-studio-1/wiki/target-audience-analysis)
[Primary User Group](https://github.com/UQdeco2800/2022-studio-1/wiki/Primary-User-Group)
[Design Committee Research](https://github.com/UQdeco2800/2022-studio-1/issues/356)
[Overview of Juicy UI](https://github.com/UQdeco2800/2022-studio-1/wiki/Juicy-UI)
[Map Design and Inspiration](https://github.com/UQdeco2800/2022-studio-1/wiki/Map-Design-and-Inspiration)
 
# **Milestones**
List of sub-features we intend to complete in the final sprint.
- [x] Analysis of existing guidelines formed by Design Committee and by other teams (Oct. 11)
- [x] Define the visual representation of Atlantis Sinks in terms of cohesion and style (Oct. 12)
- [ ] Documentation of the guidelines for a game's visual and content element (Oct. 12)
- [ ] Creating a summary in wiki section for future reference ( Oct. 18)

**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Design Style and Cohesion Guidelines Introduction](https://github.com/UQdeco2800/2022-studio-1/wiki/Design-Style-and-Cohesion-Guidelines-Introduction)

# **Team 15 Sprint 4 Members**
- Suhas Udupa (@suhasudupaa) (Suhas Udupa)
- Emma Schmidley (@schmidem) (Emma Schmidley)
- Rohan Teotia (@RohanTeo) (Rohan Teotia)
- Aleks (@a-siroki) (Aleks Siroki)
- Annabel (@Annabel-Kennedy, Annabel Kennedy)
