### ISSUE TITLE
Crystal Upgrade Pop Up

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#394]
# **Description**
**Task:** [Implement Pop Up for crystal Upgrade](#3).
**Feature:** [Crystal Modification and Enhancement ](#347 )

Create and integrate a UI Pop Up to handle upgrade of Crystal. The design and style of said pop up will be inline with buildings UI pop up. The Pop Up will include information about the crystal, benefits/cost of upgrading.
 

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 9) Create function to create UI Pop Up
- [x] Step 2 (Sep. 10) Implement button and listener to trigger Crystal Upgrade method when clicked
- [x] Step 3 (Sep. 11) Design and implement UI components (buttons, health bar)
- [x] Step 4 (Sep. 12) Implement functionality to handle insufficient funds to upgrade

 
**Completion Deadline:** Oct. 14

 
# **Documentation**

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
