### ISSUE TITLE
Increase "Juiciness" of Crystal

### ISSUE THREAD

**Issue by DarrenOoi** [UQdeco2800/2022-studio-1#395]
# **Description**
**Task:** [Increase "Juiciness" of Crystal](#394)
**Feature:** [Crystal Modification and Enhancement ](#347 )

In this sprint, the "Juiciness" of the Crystal feature is to be improved through increasing positive visual feedback and visual enjoyment factor. This is achieved through several ways such as refining the current crystal design , implementing animation and adding a screen shake effect.  
 
## SubFeature/component 

- Refine Crystal Design
   A pedestal will be designed for which the crystal will sit on, this is to signify the importance of the crystal and imply the setting of 
   the game (Ancient Greek). Existing crystal design will also be refined to include more detail and increase pixelation. 
- Screen Shake Effect
   An effect of the game screen shaking will be implemented and triggered when the crystal is upgraded, this is to imitate the 
   vibrations as more land emerge from under the water. This increases the sense of impact/movement and convey to users that 
   upgrading the crystal is significant. 
- Animation
   Animations of crystal being upgraded/destroyed will be added to increase visual enjoyment. Crystal destroyed animation is 
   particularly important to instill the feeling of helplessness and despair to the player as they watch the crystal shatter and lose colour 
   before turning black, signifying the end of the game. 

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct. 14 ) Complete design of crystal pedestal @CongxiaoZhou 
- [x] Step 2 (Oct. 14) Implement Screen Shake effect when crystal is upgraded @DarrenOoi 
- [x] Step 3 (Oct. 16) Finalise crystal + pedestal design  @sheehamishra 
- [x] Step 4 (Oct. 16) Complete design of crystal destroyed animation @sheehamishra 
- [x] Step 4 (Oct. 16) Complete design of crystal upgraded animation @KavyaMenda 
- [x] Step 4 (Oct. 17) Implement crystal destroyed/upgraded animation @zdewantoro @KavyaMenda 

 
**Completion Deadline:** Oct. 17

 
# **Documentation**

# **Members**
Sheeha Mishra (@sheehamishra) (Sheeha Mishra)
Muhammad Zahran Agung Dewantoro (@zdewantoro) (Muhammad Zahran Agung Dewantoro)
Tian Yang Ooi (@DarrenOoi) (Tian Yang Ooi)
Kavya Menda (@KavyaMenda) (Kavya)
