### ISSUE TITLE
Actions on Environmental Objects

### ISSUE THREAD

**Issue by setoaprasetyo** [UQdeco2800/2022-studio-1#40]
# **Description**
**Task:** Actions on Environmental Objects.
**Feature:** Landscape Objects(#6)

The task is to have the ability for players to perform actions to the environmental objects/hazards, obtain resources from performing said actions, and remove said obstacles from the map. Obtaining resources can be in the form of mining rocks, chopping trees, or collecting artifacts. Players can use obtained resources to build or upgrade buildings or even discover new buildings. Obtaining resources can take time and be assigned to citizens to do. The player/citizen needs to be near the object to be able to be extracted. While the object is being extracted, the progress of the action might be presented by a meter or graphically (e.g. rocks breaking). Larger objects may take longer to break or are more costly to extract but provide more resources. Objects may not provide resources and might only be destroyed to remove hazards or open up more space. Once the objects are removed, the space it occupied will no longer have collisions and is able to be built on.

# **Dependencies**
- [ ] Environmental Objects to be placed (Cobwebs, Rocks, Trees, Etc.)
- [ ] Grid Positions for objects to be placed on
- [ ] Resource types to be gathered
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Base class created (Aug. 20)
- [ ] Objects made to be actionable and removable(Aug. 23)
- [ ] Cost, duration, and obtainables (Aug.26)
- [ ] Textures/presentation
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Seto (@setoaprasetyo) (Seto Adhi Prasetyo)
