### ISSUE TITLE
Shop screens to popup migration

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2022-studio-1#419]
# **Description**
**Task:** Shop screens to popup migration
**Feature:** [Shop & Inventory refinement](#315) 

Migrate all shop screens to popups to fix the delay issue caused by ServiceLocator.
 
# **Milestones**
- [x] Implemented layout and background for shop category selection page (Oct. 14)
- [x] Link category buttons to new Item selection pages (Oct. 15)
- [x] Implemented layout for Item selection pages (Oct. 15)
- [x] Fix scaling issue (Oct. 18)
 
**Completion Deadline:** Oct. 18

# **Documentation**
- shop popup implementation & resize (https://github.com/UQdeco2800/2022-studio-1/wiki/Shop-Implementation)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Cheng-Yu Lin @Lumin-cider
