### ISSUE TITLE
Improving Defeat Scene 

### ISSUE THREAD

**Issue by RohanTeo** [UQdeco2800/2022-studio-1#430]
# **Description**
**Task:** Improving the epilogue defeat screen
**Feature:** https://github.com/UQdeco2800/2022-studio-1/issues/346

During sprint 4 our team took the initiative to lead the design committee to update the design guidelines based on user testing of the whole game. After user testing, it was found the defeat screen partially follows the guidelines and needs to be more consistent. Upon reflecting on the results, the aim is is to improve the design consistency.

# **Dependencies**
The style in which these animations will be created will be dependent on team 15's user testing: https://github.com/UQdeco2800/2022-studio-1/issues/346

 
# **Milestones**
- [ ] Resarch and Finish User testing for results (Oct. 12)
- [ ] Updating screen with new sprites (Oct. 16)
- [ ] Finalise design (Oct.. 17)
- [ ] User test (Oct. 18)
 
**Completion Deadline:** OCT. 18

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rohan Teotia (@RohanTeo ) (Rohan Teotia)
