### ISSUE TITLE
Improving Prologue Screens

### ISSUE THREAD

**Issue by suhasudupaa** [UQdeco2800/2022-studio-1#434]
# **Description**
**Task:** Improving the prologue screen
**Feature:** https://github.com/UQdeco2800/2022-studio-1/issues/346

During sprint 4 our team took the initiative to lead the design committee to update the design guidelines based on user testing of the whole game. After user testing, it was found the prologue screen did not follow all the guidelines completely and had design inconsistencies with entities that were modified in later sprints and also did not completely adhere to the updated design guidelines set by our team to the rest of the studio, upon reflection, the aim is to improve the design consistency. 
 
# **Dependencies**
The style in which these animations will be created will be dependent on team 15's user testing: https://github.com/UQdeco2800/2022-studio-1/issues/346

 
# **Milestones**
- [x] Resarch and Finish User testing for results (Oct. 12)
- [x] Updating screen with new sprites (Oct. 16)
- [x] Finalise design (Oct.. 17)
- [x] User test (Oct. 18)
 
**Completion Deadline:** OCT. 18

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Suhas udupa (@suhasudupaa) (Suhas Udupa)
