### ISSUE TITLE
Store Front Interface

### ISSUE THREAD

**Issue by Tianyuanhaimo** [UQdeco2800/2022-studio-1#44]
# **Description**
**Task:** Store Front Interface.
**Feature:** Store Feature

Users can open the store page by clicking on the button during the daytime and the store will be closed at night. In the store page, the items for sale and the amount of player gold are displayed. The user can close the shop page by clicking on the close button.
 
## **Example (optional)**
- **Quantity and price of items**: Users can open the store page to display the quantity and price of items.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Dependency 1 (#19 )

e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Store Front Interface Picture
- [ ] Click the button to display the store
- [ ] Display gold and items
- [ ] Click the button close the store
 
**Completion Deadline:** Aug. 23

e.g.

 
# **Documentation**

 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
