### ISSUE TITLE
Integrating the buying feature into the game

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2022-studio-1#47]
# **Description**
**Task:** [Integrating the buying feature into the game](#47)
**Feature:** [Shop Foundation Functionality](https://github.com/UQdeco2800/2022-studio-1/issues/4)

Player can collect gold through gold generating buildings or earned by killing enemies, these functions will likely be introduced in the future sprints.

Gold is considered as a resource in the game, along with stones and other possible resources to be introduced in future sprints, however, it is also quite different from other resources as gold is only exclusive to the shop system. On the other hand, the stone resource which team 5 is implementing can be used for building construction/upgrade.

To construct the buying feature, several steps needs to be done:
1. Detect when the player presses the buy button
2. Add the item into player's inventory
3. Deduct gold from player's inventory
4. Changes player's stat accordingly.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] detect player event when clicking the buy button
- [x] add item into the inventory
- [x] deduct gold from player
- [x] change player stat
 
**Completion Deadline:** Aug. 27

 
# **Member**
- Cheng-Yu Lin (@Lumin-cider) (Cheng-Yu Lin)
