### ISSUE TITLE
Create Artefact Class

### ISSUE THREAD

**Issue by venndiagram5** [UQdeco2800/2022-studio-1#48]
# **Create Artefact Class**
**Feature:** #4 

Create the artefact parent class that can be used to create a variety of artefacts to be sold in the store.
 
## **Example (optional)**
- **Artefact Benefits**: Artefacts can be purchased in the store and are used to benefit the main player by blunting enemy attacks or increasing the crystal health. Artefacts will be purchased using currency.

# **Dependencies**
- [x] sprite for basic artefact
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create parent class (Aug. 20)
- [x] Create functions for class (Aug. 22)
- [x] Create unit tests for class (Aug. 24)
- [x] Add sprite to artefact class (Aug. 24)
- [x] Add class to UML diagram (Aug. 24)
 
**Completion Deadline:** Aug. 24

 
# **Documentation**
- To be added
 
# **Member**
- Satya Bhasale (@venndiagram5) (@venndiagram)
