### ISSUE TITLE
Create sprites for tower types

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#51]
# **Description**
**Task:** Create sprites for tower types (#3).
**Feature:** #10 (#2)

The team is required to design and create sprites for the buildings which will be implemented in the first sprint. 

# **Dependencies**
- [x] #50 
- [x] #25 
- [x] #29 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Ideate sprite design (Aug. 21)
- [x] Create initial design of sprites (Aug. 24)
- [x] Iterate upon sprite design (Aug. 26)
- [x] Integrate sprites into game (Aug. 28)
 
**Completion Deadline:** Aug. 28

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Member**
- Harland (@harland-jensen) (Harry Jensen)
