### ISSUE TITLE
Create defensive tower

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#52]
# **Description**
**Task:** Create defensive tower(#3).
**Feature:** #10 (#2)

The team intends on creating the first specialised tower which can be purchased by players. This tower will extend upon the defensive building class, and implement combat modules, allowing it to eliminate enemies. The tower will also have range and health attributes. 

# **Dependencies**
- [x] #25 
- [x] #29 
- [x] #51 
- [x] #27 
- [x] #14 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Extend upon defensive building class (Aug. 23)
- [ ] Implement modules to give tower attributes (Aug. 25)
- [ ] Implement ability for tower to damage enemies (Aug. 27)
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Harland (@harland-jensen) (Harry Jensen)
