### ISSUE TITLE
Create specialised infrastructure (Wall) 

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#53]
# **Description**
**Task:** Create specialised infrastructure (Wall)  (#3).
**Feature:** #10 (#2)

The team intends on creating the first specialised infrastructure class, a wall which can be purchased by players. The wall will extend upon the infrastructure class, and implement health attributes. 
 
## **Example**
- **Wall benefits**: Players can purchase walls which enemies will initially path around, unless the wall is impassable in which case enemies will target wall segments

# **Dependencies**
- [x] #25 
- [x] #29 
- [ ] #27 
- [x] #14 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Expand infrastructure class (Aug. 23)
- [ ] Implement required modules to realise attributes (Aug. 25)
- [ ] Create sprites (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Harland (@harland-jensen) (Harry Jensen)
