### ISSUE TITLE
Loading of crab melee enemy into the game

### ISSUE THREAD

**Issue by cholnhial** [UQdeco2800/2022-studio-1#54]
# **Description**
**Task:** Loading of crab melee enemy into the game (#54).
**Feature:** Addition of enemies and their basic interaction with the game world (#3)

The addition of the crab enemy into the game with basic configuration similar to what is already present for boxboy ghosts. The enemy will not have all direction sprites for movement. Only one face will be used - it will be using a static sprint similar to box boy and will `ChaseTask` when main character is close and `WanderTask` for it to roam around and locate the main character.

In the future it will be improved to use other components that are more approriate for its behaviour.

# **Dependencies**

- [x] Enemy sprite for crab character (#57)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Creation of configuration class for the crab enemy (Aug. 23)
- [x] Load crab entity sprite into GameArea (Aug. 23)
- [x] NPC Factory to create crab class (Aug. 23)
- [x] Document new crab enemy on Wiki (Aug. 24)

 
**Completion Deadline:** Aug. 23

# **Documentation**
- To add link to feature on wiki
 
# **Member**
- Chol Nhial Chol (@cholnhial ) (Chol Nhial)
- Pranav (@Pranav2087) (Pranav)
- Ella West (@EllaWest038) (Ella West)
- Samantha Smart (@samsmarttt) (Samantha Smart)
