### ISSUE TITLE
Melee Enemy Design

### ISSUE THREAD

**Issue by samsmarttt** [UQdeco2800/2022-studio-1#57]
# **Description**
**Task:** Melee Enemy Character Design
**Feature:** Enemy Character Overview (#3)

Design Melee Enemy (4 Directional Sprite)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Research and ideate potential enemy characters (Aug. 20)
- [ ] Initital design of 'Crab' enemy drawn and documented (Aug. 21)
- [ ] Wiki inspiration documentation (Aug. 21)
- [ ] Draft sprite (4 Directions) (Aug. 23)
- [ ] Documentation of Enemy updated on wiki (Aug. 23)
- [ ] User Testing (Aug. 24)
- [ ] Showcase to Studio (Aug. 24)
- [ ] Edit, apply feedback, and finalise enemy design (Aug. 26)
- [ ] Documentation of Enemy updated on wiki (Aug. 28)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of feature](../wiki/Enemies)
 
# **Member**
- Samantha Smart (samsmarttt) (Samantha Smart)

**Comment by samsmarttt** [comment]
**_23/08/2022_**
To create a consist design across various teams interacting with the characters (main and enemies), the terrain, and resources collaboration with @hblakeway @schmidem after studio class, discussed and finalised the design guidelines of the enemies. This information was then provided to the rest of the studio in a google doc, dismissing varied design perspectives which would have resulted in a messy and inconsistent game design.

_Key topics discussed included:_ 
-	The canvas size of the enemies and terrain 
-	Enemy & Main Character Guidelines: 
o	3D, flat front facing
-	Stationary Objects (Buildings, Terrain etc.)
o	Isometric (according to grid, 30-degree angle)
-	Art Style: 1-pixel dark colour for outline, no pixel blurring

**Comment by samsmarttt** [comment]
**_26/08/2022_**
@schmidem and i had a meeting that night to finalise the sizes of the entities which had been discussed within the studio meeting and clear any lingering confusion about other design aspects. The sizes of the entities were originally created however, were then enlarged by 1.5x to allow for adequate detail to be applied - during implementation into the game, they would be scaled down. It was important to establish early on the assigned canvas size considering varied sizes would result in an entity to look more pixelated than another.

_Original Size Mock-up:_
	Terrain Tree: 40 x 60
	Main Character: 50 x 50
	Enemies: 40 x 40

_Finalised Size Mock-up:_
Terrain Tree: 60 x 10
	Main Character: 75 x 75
	Enemies: 60 x 60

**Comment by samsmarttt** [comment]
_**29/08/2022**_
@hblakeway and @samsmarttt finalised the designs of the enemies, showcased front and back of designs - provided constructive feedback regarding the highlighting of the eel to break up the body, able to distingush between elements of the eel. Feedback resulted in the crab hook to enlarge!

**Comment by samsmarttt** [comment]
_**23/08/2022**_
Studio user testing with all of team 11. They provided constructive criticism in regard to the low fidelity crab design. Suggestions: enlarging the claw size to draw the attention of the user and to make the crab more scary, addition of an animated face. Both of these suggestions were implemented! Thanks team 11
