### ISSUE TITLE
Stone Quarry Low Fidelity Prototype [Design]

### ISSUE THREAD

**Issue by luke4641942** [UQdeco2800/2022-studio-1#58]
# **Description**
**Task:** [Stone Quarry Low Fidelity Prototype [Design]](#3).
**Feature:** [Resource Management (Including Resource Buildings)](#11)

For the design side of the team, this task was designed to get collate everyones initial ideas and give the rest of the team a variety of ideas and design features to choose from. Main focus is to gather inspiration from various sources and put some low fidelity sketches before the team to finalise the design.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Research for inspiration from relevant movies, games and other various pop culture (Aug. 20)
- [ ] Draw up a few page of low fidelity drawings with a highlight for variety (Aug. 21)
- [ ] Discuss which style of mine the team likes then create a list of the best features (Aug. 22)
- [ ] Final design and list of design features to be finalised before moving onto High Fidelity Task (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Luke Graham (@luke4641942) (Luke Graham)
