### ISSUE TITLE
Stone Quarry High Fidelity Prototype [Design]

### ISSUE THREAD

**Issue by luke4641942** [UQdeco2800/2022-studio-1#59]
# **Description**
**Task:** [Stone Quarry High Fidelity Prototype [Design]](#3).
**Feature:** [Resource Management (Including Resource Buildings)](#11)

Extending from Task #58, this task is set for the designers to finalise the design, create high fidelity drawings and provide the coding team with a implementable sprite. 

# **Dependencies**
- [ ] Required to finish the ideation and low fidelity phase (#58 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Finalise Design (Aug. 23)
- [ ] Have low fidelity final design drawn up and revise with team (Aug. 24)
- [ ] Complete high fidelity drawing (Aug. 28)
- [ ] Complete sprite for coding team (Aug. 28)
- [ ] Help coding team to implement (Aug 30)
 
**Completion Deadline:** Aug. 30

# **Extras**
If we have left over time...
- [ ] Implement simple animations for the mine (Aug. 30)
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Luke Graham (@luke4641942 ) (Luke Graham)
