### ISSUE TITLE
Addition of a healthbar component for enemies and other entities

### ISSUE THREAD

**Issue by cholnhial** [UQdeco2800/2022-studio-1#60]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#3 )

This task adds a renderable component that displays health by using `CombatStatsComponent` attached to the entity. The healthbar is to be displayed on top of the entity.
 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step Create healthbar component (Aug. 22)
- [x] Get healthbar component to be rendered on enemy and move with enemy (Aug. 22)
- [x] Position healthbar component at the top of enemy (Ghosts) (Aug. 23)
-
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Chol Nhial (@cholnhial ) (Chol Nhial)
