### ISSUE TITLE
Obstacle Programming

### ISSUE THREAD

**Issue by MichelleAsWell** [UQdeco2800/2022-studio-1#7]
# **Description**
**Task:** Obstacle Programming.
**Feature:** [Landscape Objects](#6)

`Obstacle` inherits from `Landscape Object` and is a type of object generated on map creation. `Obstacles` have collision mechanics, and reward resources when removed from the map by the player. Collision mechanics will be implemented in an interface, and include entity slowing and redirection. Obstacles will have (at least) the following features
Inherited from Landscape Object: 
- boundaries
- sprite
- location
New: 
- yielded resources
- collision mechanics (these will be inherited from collision interfaces)

# **Dependencies**
- [x] Generic `Landscape Object` class must be created
- [x] Texture(s) must be created for obstacles
- [x] `Obstacles` must be placed on the map on map creation

# **Milestones**
- [x] Base class created (Aug. 20)
- [x] Collision interfaces implemented (Aug. 23)
- [x] Specific object types implemented (Aug. 26)
- [x] Textures added (Aug. 28)
 
**Completion Deadline:** Aug. 26

# **Documentation**
- [Main description of feature](../wiki/Landscape-Objects)
- TODO [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michelle (@MichelleAsWell) (Michelle Sands)

**Comment by MichelleAsWell** [comment]
Commenting to formalise an agreement our team came to a while ago with regards to #40 - This ticket encompasses collision interactions, slows, etc. for **all objects**, not just obstacles, and does not include removal or resource grant (the original ticket assumed obstacles and artefacts would be programmed by two separate people - considering the overlap in behaviour we decided against this)
