### ISSUE TITLE
Enemy Team Design Cross Collaboration Team 9

### ISSUE THREAD

**Issue by hblakeway** [UQdeco2800/2022-studio-1#71]
# **Description**
**Task:** Design Collaboration
**Feature:** Ensure cohesion of enemy characters

Team 1 and Team 9 will collaborate to ensure designs of enemies are cohesive with one another. 
 
# **Discussion**
This ticket acts as a Github thread between the two teams. 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide on design features (Outline, Size, Pixel Style) (Aug. 26)
- [x] Cross Check front designs (Aug. 28)
- [x] Cross Check back designs (Aug. 30)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of ranged enemies](../wiki/Ranged-Enemies)
 - [Main description of melee enemies](../wiki/Melee-Enemies)
 - 
# **Member**
- Team 1
- Team 9

**Comment by hblakeway** [comment]
Hey there, do you know if we are putting a shadow under enemies? Might be a question for the whole studio?

**Comment by hblakeway** [comment]
![back eel](https://user-images.githubusercontent.com/88036522/187070244-9359bccc-113a-444b-992d-540d2cb1399a.png)
Thoughts on this for the back view? Is the angle ok?

**Comment by samsmarttt** [comment]
_**28/08/2022**_
28/08/2022
@hblakeway and @samsmarttt had a meeting to review one another’s enemy sprites, making sure that the design guidelines were being followed. Consequently, improving cohesion across the two characters regarding the theme and art style -feedback was given to help improve designs, colour contrasting, and the overall perspective of the enemy. One of the topics discussed included the perspective of the crab facing backwards, recognised my error and it was fixed!

**Comment by hblakeway** [comment]
29/08/2022
@samsmarttt  and @hblakeway had a meeting to review the changes made from the feedback received from user testing regarding the ranged enemy. Here feedback was provided to ensure the art style was achieved and consistent amongst both teams.

**Comment by samsmarttt** [comment]
**_23/08/2022_**
To create a consist design across various teams interacting with the characters (main and enemies), the terrain, and resources collaboration with @hblakeway @schmidem after studio class, discussed and finalised the design guidelines of the enemies. This information was then provided to the rest of the studio in a google doc, dismissing varied design perspectives which would have resulted in a messy and inconsistent game design.

Key topics discussed included:

The canvas size of the enemies and terrain
Enemy & Main Character Guidelines:
o 3D, flat front facing
Stationary Objects (Buildings, Terrain etc.)
o Isometric (according to grid, 30-degree angle)
Art Style: 1-pixel dark colour for outline, no pixel blurring
