### ISSUE TITLE
Ranged Enemy Design 

### ISSUE THREAD

**Issue by hblakeway** [UQdeco2800/2022-studio-1#75]
# **Description**
**Task:** Ranged enemy design
**Feature:** Ranged enemy design which this contributes to implementing (#3 )

We aim to design a 4 directional ranged enemy 

# **Dependencies**
- Design objectives need to be clear amongst all character teams
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Research character ideas (Aug. 20)
- [x] Sketch low fidelity ideas (Aug. 21)
- [x] Discuss ideas/features to be included/improved on (Aug. 22)
- [x] Discuss design guidelines with collaborating teams (Aug. 24)
- [x] Sketch revised medium fidelity characters (Aug 28)
- [x] User Testing (Aug 29)
- [x] Apply final changes and refinements (Aug 30)
- [x] Complete Wiki Page (Aug 30)
 
**Completion Deadline:** Aug. 30

 
# **Documentation**
- [Main description of enemy feature](../wiki/Ranged-Enemies)
- [Main description of enemy design process](https://github.com/UQdeco2800/2022-studio-1/wiki/Ranged-Enemy-Design-Process)
- [Main description of user testing](../wiki/Ranged-User-Testing)
- Miro Inspiration board used in the planning of the enemy (https://miro.com/app/board/uXjVPdp4UuM=/)

 
# **Member**
- Heather Blakeway (heatherBlakeway)
