### ISSUE TITLE
Animations for Resource Building

### ISSUE THREAD

**Issue by Naman-Agarwal1608** [UQdeco2800/2022-studio-1#76]
# **Description**
**Task:** [Adding animations to the resource building](#3).
**Feature:** [https://github.com/UQdeco2800/2022-studio-1/issues/11](#2)

This task is for adding animations to our resource building. Main idea is to know how the things works and we can add animations to other entities and objects.
 
# **Dependencies**
- [ ] Different sprites from designers (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Different sprites generated (Aug. 25)
- [ ] Addition of animations (Aug. 27)
- [ ] Testing and Evaluation (Aug. 29)

 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
