### ISSUE TITLE
Shop Extended Functionality

### ISSUE THREAD

**Issue by mackenziekerr1** [UQdeco2800/2022-studio-1#94]
# **Description**
Extending the functionality of the shop by fixing any existing issues that arose when merging with other teams during Sprint 1, creating a larger catalogue of products and categories available in the shop, implementing purchasing constraints and storing purchased items in an inventory.

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [ ] Goal 1 (Sep. 2)
- [ ] Final iterations on designs
- [ ] Determine with the storyline team which items will be available in the shop

- [ ] Goal 2 (Sep 5)
- [ ] Diagram of all items available including their features & price
- [ ] Creation of new assets to be included in the shop
- [ ] Creation of assets for purchasing constraints

- [ ] Goal 3 (Sep. 9)
- [ ] Fix shop interface scaling
- [ ] Implementation of carousel function 
- [ ] Wiki documentation of design iterations

- [ ] Goal 4 (Sep. 11)
- [ ] Implementation of purchasing constraints (eg. only being able to buy an item once)
- [ ] Wiki documentation of new design assets created 

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Inventory Interface
- [ ] Implementation of an accessible inventory

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)
