### ISSUE TITLE
More types of structures

### ISSUE THREAD

**Issue by harland-jensen** [UQdeco2800/2022-studio-1#96]
# **Description**
The team intends on implementing a minimum of two new towers, and one new 'trap' building. These structures will build upon existing functionality while adding further interaction with other game features, i.e. enemies, shop, resources, etc. Buildings will be able to be bought from Shop and interact with Enemies along with using Resources for upgrades. 

## Design Component
The design team members will design and test new sprites for different types of defense buildings and new 'trap' style buildings. Trap defense structure will be a entity that enemies can walk over, but when they do walk over it they incur damage and slow down.

## Software Development Component
The software development team members will create custom components for the different types of structures and their functionality along with creating a structure service to manage them anywhere in the game.

# **Dependencies**
- Shop Feature (buying and selling structures #94)
- Enemies Feature (damaging enemies and taking damage from enemies #107)
- Building UI (integrating with the user interface to manage, upgrade, and delete buildings from the game #97)

# **Milestones**
- [ ] #131
- [x] #132
- [x] #133
- [x]  #152 
- [x] #153
- [x] #154

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Building Animation
- [ ] Building effects (slow on damaging enemies)
- [ ] Building range capability indicator
- [ ] Fix building HP display
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Jonathan Allen (jonooallen) (Jonathan Allen)
- Harland (@harland-jensen) (Harland Jensen)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by mackenziekerr1** [comment]
hey team 7, just dropping a comment in here from team 10 (shop team) to confirm that we have used your building sprites as inspiration to design the icons for the attack buildings & wall to be purchased in the shop as shown below. any questions let me know!
![Wall](https://user-images.githubusercontent.com/109883395/189620429-3e9be8d8-1d45-45b6-8ff0-0c60d8540d60.png)
![Attack building](https://user-images.githubusercontent.com/109883395/189620437-bedd39ff-0c02-46ea-b489-4c2267466d4e.png)
