### ISSUE TITLE
Building UI

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#97]
# **Description**
The Building UI will be on the main game screen and will pop up when a building is clicked by a user. From this interface, the building can be updated or sold. This will also be an easy way to check the status of the building. This interface will hopefully increase usability and enjoyment when playing the game. 

## Component
- Wireframes - to confirm with other teams that this fits well with other elements of the game that has already been established. 
- User Testing - User testing will be used to check that the interface is usable and enjoyable to use. 
- JUnit tests - To determine the suitability of code. 
- Design - designing the buttons and the pop-up itself. 
- Implementation - Implementing the design and general concept into the game. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
**Goal 1 (Sep 2)**
- [x] #103
- [x] Confirm with Team 2 if concept fit the storyline of the game.
- [x] Confirm with Team 7 if this fits with their already implemented code and concept. 

**Goal 2 (Sep 5)**
- [x] #98
- [x] Have designs on buttons completed (exit, update, and sell)
- [x] Have the design of the pop-up finished 
- [ ] Upload all design features into the game

**Goal 3 (Sep 8)**
- [ ] Have the UI interface pop-up on click 
- [ ] Have the exit button implemented and you can close the pop-up
- [ ] #100
- [ ] #99

**Goal 4 (Sep. 11)**
- [ ] #104
- [ ] Fix any last issues with the code and determine functionality 

**Completion Deadline:** September 14

# **Extras (optional)**
- [ ] Talk to the sound effect team and see if we can help integrate a sound effect for the pop-up

# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)

**Comment by Olivialeighton** [comment]
Removed team 2 as they are not working on currency and building upgrades in this sprint.
