### ISSUE TITLE
JUnits to be completed for

### ISSUE THREAD

**Issue by Olivialeighton** [UQdeco2800/2022-studio-1#99]
# **Description**
Write JUnit Tests for the back-end coding of the UI Building. There will be statistics called from the building team code and also the game code itself. Therefore there will need to be testing to check that all values called are correct and working well. 

## Component
- Writing the code of the statistics will be needed to be completed before the JUnit's is made. 
- JUnit tests written 
- Also create a Youtube video of the functionality as not all will be tested. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

**Goal 1 (Sep 8)**
- [x] Have the statistics linked to the to the pop-up interface
- [x] Have the UI interface pop-up on click 
- [ ] Write J Unit testing 

**Goal 2 (Sep. 11)**
- [ ] Final User Testing to be completed to determine any bugs in the code
- [ ] Fix any last issues with the code and determine functionality 

**Completion Deadline:** September 14

# **Members**
Olivia Leighton (@Olivialeighton)
Bagus Prabowo Reksoprodjo (@baguspr)
Tara-Jade Garnsworthy (@tgarnsworthy)
Syed Muhammad Zahir (@ChevScore)
